import type{StrategyLabScenarioResult}from"./strategyHistoryLab";
export type RobustWindowV130={startDate:string;endDate:string;returnA:number;returnB:number;gap:number;volA:number|null;volB:number|null;maxDdA:number;maxDdB:number;leader:"A"|"B"|"tie";lowerVol:"A"|"B"|"tie";shallowerDd:"A"|"B"|"tie"};
export type StrategyRobustnessV130={available:boolean;days:number;windows:RobustWindowV130[];aLeadShare:number|null;bLeadShare:number|null;aLowerVolShare:number|null;bLowerVolShare:number|null;aShallowerDdShare:number|null;bShallowerDdShare:number|null;aTripleShare:number|null;bTripleShare:number|null;bestA:RobustWindowV130|null;bestB:RobustWindowV130|null;reason:string|null};
const sd=(v:number[])=>{if(v.length<2)return null;const m=v.reduce((s,x)=>s+x,0)/v.length;return Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/(v.length-1))*Math.sqrt(252)},cmp=(a:number,b:number,lower=false)=>Math.abs(a-b)<1e-10?"tie":lower?(a<b?"A":"B"):(a>b?"A":"B");
export function buildStrategyRobustnessV130(a:StrategyLabScenarioResult|null,b:StrategyLabScenarioResult|null,days=63):StrategyRobustnessV130{
 const empty=(reason:string):StrategyRobustnessV130=>({available:false,days,windows:[],aLeadShare:null,bLeadShare:null,aLowerVolShare:null,bLowerVolShare:null,aShallowerDdShare:null,bShallowerDdShare:null,aTripleShare:null,bTripleShare:null,bestA:null,bestB:null,reason});if(!a?.available||!b?.available||!Number.isInteger(days)||days<2)return empty("Нужны два доступных сценария и корректное окно.");
 const mb=new Map(b.curve.map(x=>[x.date,x.value])),p=a.curve.filter(x=>mb.has(x.date)).map(x=>({date:x.date,a:x.value,b:mb.get(x.date)!})).filter(x=>x.a>0&&x.b>0);if(p.length<=days)return empty("Недостаточно общих точек.");
 const windows:RobustWindowV130[]=[];for(let i=days;i<p.length;i++){const q=p.slice(i-days,i+1),s=q[0]!,e=q.at(-1)!,ra:number[]=[],rb:number[]=[];let pa=s.a,pb=s.b,dda=0,ddb=0;for(let k=1;k<q.length;k++){const x=q[k]!;ra.push(x.a/q[k-1]!.a-1);rb.push(x.b/q[k-1]!.b-1);pa=Math.max(pa,x.a);pb=Math.max(pb,x.b);dda=Math.min(dda,x.a/pa-1);ddb=Math.min(ddb,x.b/pb-1)}const returnA=e.a/s.a-1,returnB=e.b/s.b-1,gap=returnA-returnB,volA=sd(ra),volB=sd(rb);windows.push({startDate:s.date,endDate:e.date,returnA,returnB,gap,volA,volB,maxDdA:dda,maxDdB:ddb,leader:cmp(returnA,returnB),lowerVol:volA==null||volB==null?"tie":cmp(volA,volB,true),shallowerDd:cmp(Math.abs(dda),Math.abs(ddb),true)})}
 const n=windows.length,share=(f:(x:RobustWindowV130)=>boolean)=>windows.filter(f).length/n;return{available:true,days,windows,aLeadShare:share(x=>x.leader==="A"),bLeadShare:share(x=>x.leader==="B"),aLowerVolShare:share(x=>x.lowerVol==="A"),bLowerVolShare:share(x=>x.lowerVol==="B"),aShallowerDdShare:share(x=>x.shallowerDd==="A"),bShallowerDdShare:share(x=>x.shallowerDd==="B"),aTripleShare:share(x=>x.leader==="A"&&x.lowerVol==="A"&&x.shallowerDd==="A"),bTripleShare:share(x=>x.leader==="B"&&x.lowerVol==="B"&&x.shallowerDd==="B"),bestA:[...windows].filter(x=>x.gap>1e-10).sort((x,y)=>y.gap-x.gap)[0]??null,bestB:[...windows].filter(x=>x.gap<-1e-10).sort((x,y)=>x.gap-y.gap)[0]??null,reason:null};
}