'use strict';

module.exports = function registerPayoutCalendar(app, deps) {
  const { tbankRequest, buildDashboard, getAccounts, selectAccount, getOperations, isIncomeOperation, operationCash } = deps || {};
  const INSTRUMENTS='tinkoff.public.invest.api.contract.v1.InstrumentsService/',CACHE_MS=60000;let cache=null,lastGood=null;
  const moneyValue=v=>{if(v==null)return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;if(typeof v==='string')return Number(v)||0;return(Number(v.units??v.unit??0)||0)+(Number(v.nano??v.nanos??0)||0)/1e9};
  const quantityValue=v=>v==null?0:(typeof v==='number'||typeof v==='string'?Number(v)||0:moneyValue(v));
  const safeDate=v=>{if(!v)return null;const d=v instanceof Date?v:new Date(v);return Number.isFinite(d.getTime())?d:null},iso=v=>{const d=safeDate(v);return d?d.toISOString():null},monthKey=v=>{const d=safeDate(v);return d?`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`:null},round2=n=>Math.round((Number(n)||0)*100)/100;
  const monthStart=v=>{const d=safeDate(v);return d?new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)):null};
  const nextMonth=v=>{const d=monthStart(v);return d?new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)):null};
  function taxEstimate(g){g=Math.max(0,Number(g)||0);const tax=Math.min(g,2400000)*.13+Math.max(0,g-2400000)*.15;return{gross:g,tax,net:g-tax,rate:g?tax/g*100:13}}function eventNet(g){const t=taxEstimate(g);return{gross:round2(t.gross),tax:round2(t.tax),net:round2(t.net),taxRate:round2(t.rate)}}
  function classifyAsset(a){const type=String(a?.instrumentType||a?.type||'').toUpperCase(),ticker=String(a?.ticker||'').toUpperCase(),name=String(a?.name||'').toLowerCase();if(type.includes('BOND')||/^SU\d/.test(ticker)||/^RU000A/.test(ticker)||/офз|облигац/.test(name))return'bond';if(type.includes('SHARE')||type.includes('STOCK'))return'share';return'other'}
  async function fetchAssetSchedule(asset,from,horizon){const kind=classifyAsset(asset),instrumentId=asset?.instrumentUid||asset?.figi||asset?.instrumentId,qty=Math.max(0,quantityValue(asset?.quantity));if(!instrumentId||qty<=0||kind==='other')return[];const queryTo=new Date(horizon);queryTo.setUTCMonth(queryTo.getUTCMonth()+12);if(kind==='bond'){const data=await tbankRequest(`${INSTRUMENTS}GetBondCoupons`,{instrumentId,from:from.toISOString(),to:queryTo.toISOString()}),rows=Array.isArray(data?.events)?data.events:[];return rows.map(row=>{const date=safeDate(row?.couponDate||row?.coupon_date),per=moneyValue(row?.payOneBond||row?.pay_one_bond),calc=eventNet(per*qty),couponRaw=Number(row?.couponNumber??row?.coupon_number),couponNumber=Number.isFinite(couponRaw)&&couponRaw>0?Math.trunc(couponRaw):null,scheduleInstrument=asset?.instrumentUid||asset?.figi||instrumentId,scheduleId=couponNumber?`COUPON:${scheduleInstrument}:${couponNumber}`:null;return{kind:'COUPON',ticker:asset?.ticker||asset?.name||instrumentId,name:asset?.name||asset?.ticker||instrumentId,figi:asset?.figi||null,instrumentUid:asset?.instrumentUid||null,date:iso(date),recordDate:iso(row?.fixDate||row?.fix_date),quantity:qty,perSecurity:round2(per),currency:row?.payOneBond?.currency||row?.pay_one_bond?.currency||'rub',couponNumber,scheduleId,...calc,confidence:'HIGH',source:'TBANK_COUPON_SCHEDULE'}}).filter(x=>x.date&&x.gross>0)}const data=await tbankRequest(`${INSTRUMENTS}GetDividends`,{instrumentId,from:from.toISOString(),to:queryTo.toISOString()}),rows=Array.isArray(data?.dividends)?data.dividends:[];return rows.filter(row=>!/cancel/i.test(String(row?.dividendType||row?.dividend_type||''))).map(row=>{const recordDate=safeDate(row?.recordDate||row?.record_date),paymentDate=safeDate(row?.paymentDate||row?.payment_date),lastBuyDate=safeDate(row?.lastBuyDate||row?.last_buy_date),per=moneyValue(row?.dividendNet||row?.dividend_net),calc=eventNet(per*qty);return{kind:'DIVIDEND',ticker:asset?.ticker||asset?.name||instrumentId,name:asset?.name||asset?.ticker||instrumentId,figi:asset?.figi||null,instrumentUid:asset?.instrumentUid||null,date:iso(paymentDate||recordDate||lastBuyDate),recordDate:iso(recordDate),lastBuyDate:iso(lastBuyDate),quantity:qty,perSecurity:round2(per),currency:row?.dividendNet?.currency||row?.dividend_net?.currency||'rub',...calc,confidence:paymentDate?'HIGH':'MEDIUM',source:'TBANK_DIVIDEND_SCHEDULE'}}).filter(x=>x.date&&x.gross>0)}
  function factObservation(account,ops,now){
    const yearStart=new Date(Date.UTC(now.getUTCFullYear(),0,1));
    const opened=safeDate(account?.openedDate||account?.openDate||account?.createdAt||account?.createdDate);
    const opDates=(Array.isArray(ops)?ops:[]).map(op=>safeDate(op?.date)).filter(Boolean).sort((a,b)=>a-b);
    const fallbackStart=opDates[0]||null;
    const rawStart=opened||fallbackStart;
    if(!rawStart)return{available:false,from:null,to:iso(now),completeMonths:[],partialMonths:[],basis:'UNRESOLVED_START'};
    const from=rawStart>yearStart?rawStart:yearStart;
    const currentMonth=monthStart(now),openingMonth=monthStart(from);
    const completeMonths=[];
    const startsOnFirst=from.getUTCDate()===1;
    let cursor=startsOnFirst?openingMonth:nextMonth(openingMonth);
    while(cursor&&currentMonth&&cursor<currentMonth){completeMonths.push(monthKey(cursor));cursor=nextMonth(cursor)}
    const partial=new Set();
    if(openingMonth&&currentMonth&&openingMonth<=currentMonth&&(!startsOnFirst||openingMonth.getTime()===currentMonth.getTime()))partial.add(monthKey(openingMonth));
    if(currentMonth)partial.add(monthKey(currentMonth));
    for(const key of completeMonths)partial.delete(key);
    return{available:true,from:iso(from),to:iso(now),completeMonths,partialMonths:[...partial].filter(Boolean).sort(),basis:opened?'ACCOUNT_OPEN_DATE':'FIRST_OPERATION_DATE'};
  }
  function currentYearActual(ops,now,account){const year=now.getUTCFullYear(),rows=(Array.isArray(ops)?ops:[]).filter(op=>{const d=safeDate(op?.date);return d&&d.getUTCFullYear()===year&&(!isIncomeOperation||isIncomeOperation(op))}).map(op=>{const d=safeDate(op?.date),cash=Math.abs(operationCash?Number(operationCash(op))||0:moneyValue(op?.payment)),type=String(op?.type||'').toUpperCase(),name=String(op?.name||'').toLowerCase(),kind=type.includes('DIVIDEND')||name.includes('дивид')?'DIVIDEND':type.includes('COUPON')||name.includes('купон')?'COUPON':'INCOME';return{kind,ticker:op?.ticker||op?.figi||op?.name||'—',name:op?.name||op?.ticker||op?.figi||'—',figi:op?.figi||null,instrumentUid:op?.instrumentUid||null,date:iso(d),net:round2(cash),gross:null,tax:null,currency:'rub',source:'TBANK_OPERATION',status:'FACT'}}).filter(x=>x.net>0).sort((a,b)=>new Date(b.date)-new Date(a.date));return{year,items:rows,totalNet:round2(rows.reduce((s,x)=>s+x.net,0)),count:rows.length,observation:factObservation(account,ops,now)}}
  const buildMonths=(now,events)=>Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+i,1)),key=monthKey(d),items=events.filter(e=>monthKey(e.date)===key);return{key,year:d.getUTCFullYear(),month:d.getUTCMonth()+1,gross:round2(items.reduce((s,x)=>s+(+x.gross||0),0)),tax:round2(items.reduce((s,x)=>s+(+x.tax||0),0)),net:round2(items.reduce((s,x)=>s+(+x.net||0),0)),count:items.length,items}});
  async function buildPayouts(){const now=new Date(),to=new Date(now);to.setUTCFullYear(to.getUTCFullYear()+1);const dashboard=await buildDashboard(),assets=Array.isArray(dashboard?.assets)?dashboard.assets:Array.isArray(dashboard?.portfolio?.assets)?dashboard.portfolio.assets:[],eligible=assets.filter(a=>quantityValue(a?.quantity)>0&&['bond','share'].includes(classifyAsset(a))),future=[],errors=[],resolved=new Set();for(let i=0;i<eligible.length;i+=3){const batch=eligible.slice(i,i+3),rows=await Promise.all(batch.map(async a=>{const key=a?.ticker||a?.figi||'—';try{const x=await fetchAssetSchedule(a,now,to);resolved.add(key);return x}catch(err){errors.push({ticker:key,error:err?.message||String(err)});return[]}}));future.push(...rows.flat())}const seen=new Set(),events=future.filter(e=>String(e.currency||'rub').toLowerCase()==='rub').filter(e=>{const d=safeDate(e.date);return d&&d>=now&&d<=to}).filter(e=>{const k=e.scheduleId||[e.kind,e.instrumentUid||e.figi||e.ticker,e.date,e.perSecurity,e.quantity].join('|');if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(a.date)-new Date(b.date));let actual={year:now.getUTCFullYear(),items:[],totalNet:0,count:0,observation:{available:false,from:null,to:iso(now),completeMonths:[],partialMonths:[],basis:'UNAVAILABLE'}};try{if(getAccounts&&selectAccount&&getOperations){const account=selectAccount(await getAccounts());if(account?.id){const ops=await getOperations(account.id);actual=currentYearActual(ops,now,account)}}}catch(err){errors.push({ticker:'FACT',error:err?.message||String(err)})}const gross=round2(events.reduce((s,x)=>s+x.gross,0)),tax=round2(events.reduce((s,x)=>s+x.tax,0)),net=round2(events.reduce((s,x)=>s+x.net,0)),months=buildMonths(now,events),next=events[0]||null,resolvedAssets=resolved.size,coverageRatio=eligible.length?resolvedAssets/eligible.length:1,couponScheduleEvents=events.filter(e=>e.kind==='COUPON').length,couponScheduleIdentified=events.filter(e=>e.kind==='COUPON'&&e.scheduleId).length;return{version:'7.16.0',generatedAt:now.toISOString(),period:{from:now.toISOString(),to:to.toISOString()},basis:'CURRENT_HOLDINGS_FULL_12M',displayBasis:'GROSS_SCHEDULED_PAYOUTS',actual,forecast:{gross,tax,net,count:events.length},next:next?{...next,days:Math.max(0,Math.ceil((new Date(next.date)-now)/86400000))}:null,months,events,coverage:{eligibleAssets:eligible.length,scheduledEvents:events.length,resolvedAssets,coverageRatio:round2(coverageRatio),errors},identity:{couponScheduleEvents,couponScheduleIdentified,couponScheduleCoverage:couponScheduleEvents?round2(couponScheduleIdentified/couponScheduleEvents):1,basis:'TBANK_COUPON_NUMBER'},integrity:{complete:errors.filter(x=>x.ticker!=='FACT').length===0&&coverageRatio>=.95,minimumCoverage:.95},note:'Будущие выплаты показываются начисленными (gross). Купонное расписание дедуплицируется по instrument identity + T-Bank coupon_number, когда он доступен. FACT-период имеет явную границу наблюдения; НДФЛ отдельно как оценка.'}}
  app.get('/api/payouts',async(req,res)=>{try{if(cache&&Date.now()-cache.createdAt<CACHE_MS){res.setHeader('Cache-Control','no-store');return res.json(cache.data)}const data=await buildPayouts(),eligible=Number(data?.coverage?.eligibleAssets)||0,count=Number(data?.forecast?.count)||0,complete=!!data?.integrity?.complete;if(eligible>0&&(!complete||count===0)){if(lastGood){res.setHeader('Cache-Control','no-store');return res.json({...lastGood,stale:true,warning:'Incomplete T-Bank payout response rejected; showing last complete schedule.'})}const err=new Error(`Incomplete payout schedule: resolved ${data?.coverage?.resolvedAssets||0}/${eligible}, events ${count}`);err.code='PAYOUT_INCOMPLETE';throw err}cache={createdAt:Date.now(),data};lastGood=data;res.setHeader('Cache-Control','no-store, no-cache, must-revalidate');res.json(data)}catch(err){if(lastGood){res.setHeader('Cache-Control','no-store');return res.json({...lastGood,stale:true,warning:err?.message||'Temporary payout API error'})}res.status(503).json({version:'7.16.0',available:false,integrity:'INCOMPLETE',error:err?.message||'Payout calendar unavailable'})}})
};