services:
  - type: web
    name: tinvest-pocket-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TINvest_API_TOKEN
        sync: false
