import{lazy,Suspense,useMemo,useState}from"react";import type{HistoryPoint,PositionSnapshot}from"../../../v2/src/lib/portfolioApi";import type{V3HomeViewModel}from"../home/homeViewModel";import type{V3IncomeModel}from"../income/V3Income";import{V3HistorySparkline}from"../home/V3HistorySparkline";import{CorePortfolioView,CorePerformanceView,CoreStructureView}from"./CoreNativeViews";import{CoreIncomeCockpit}from"./CoreIncomeCockpit";import{CorePayoutCalendar}from"./CorePayoutCalendar";import{CoreAnalyticsCockpit}from"./CoreAnalyticsCockpit";import{CoreRiskView,CoreIncomeHistoryView}from"./CoreDeepViews";import{CoreMarketView,CoreRebalanceView}from"./CoreMarketTools";import"./coreProductSurface.css";
const V3OperationsDepth=lazy(()=>import("../operations/V3OperationsDepth").then(m=>({default:m.V3OperationsDepth}))),V3AnalysisToolbox=lazy(()=>import("../analysis/V3AnalysisToolbox").then(m=>({default:m.V3AnalysisToolbox})));
type Area="overview"|"portfolio"|"performance"|"income"|"analytics"|"market"|"tools";const money=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0}),pct=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1,signDisplay:"exceptZero"}),m=(v:number|null)=>v==null?"—":money.format(v)+" ₽",p=(v:number|null)=>v==null?"—":pct.format(v)+"%";
const NAV:[Area,string][]=[["overview","Обзор"],["portfolio","Портфель"],["performance","Результат"],["income","Выплаты"],["analytics","Анализ"],["market","Рынок"],["tools","Инструменты"]];
export function CoreProductSurface({home,positions,history,income,connection}:{home:V3HomeViewModel;positions:PositionSnapshot[];history:HistoryPoint[];income:V3IncomeModel;connection:{state:string;reason:string|null;refresh:()=>Promise<void>;refreshing:boolean}}){const[area,setArea]=useState<Area>("overview"),[portfolioTab,setPortfolioTab]=useState<"assets"|"operations">("assets"),[incomeTab,setIncomeTab]=useState<"flow"|"calendar"|"history">("flow"),[analyticsTab,setAnalyticsTab]=useState<"overview"|"risk"|"structure">("overview");const trusted=home.isTrusted,total=positions.reduce((s,x)=>s+x.currentValue,0),top=useMemo(()=>[...positions].sort((a,b)=>b.currentValue-a.currentValue).slice(0,5),[positions]),classes=useMemo(()=>{const x={stocks:0,bonds:0,other:0};positions.forEach(v=>{const t=(v.instrumentType||"").toLowerCase();if(t.includes("bond"))x.bonds+=v.currentValue;else if(t.includes("share")||t.includes("stock"))x.stocks+=v.currentValue;else x.other+=v.currentValue});return x},[positions]);const go=(x:Area)=>{setArea(x);window.scrollTo({top:0,behavior:"smooth"})};return <div className="qproduct">
<header className="qp-top"><button className="qp-brand" onClick={()=>go("overview")}><i>Q</i><span><b>QVANIX</b><small>{home.accountName||"Портфель"}</small></span></button><button className={"qp-sync "+(trusted?"ok":"")} onClick={()=>void connection.refresh()} disabled={connection.refreshing}><i/>{trusted?"LIVE":connection.state==="loading"?"SYNC":"OFFLINE"}</button></header>
<nav className="qp-sections">{NAV.map(([id,label])=><button key={id} className={area===id?"active":""} onClick={()=>go(id)}>{label}</button>)}</nav>
{!trusted&&<div className="qp-trust"><div><b>{connection.state==="loading"?"Подключаем данные":"Данные временно недоступны"}</b><span>{connection.reason??"Финансовые показатели не показываем до подтверждения источника."}</span></div><button onClick={()=>void connection.refresh()}>Повторить</button></div>}
<main className="qp-main">
{area==="overview"&&<><section className="qp-hero"><div><small>КАПИТАЛ</small><strong>{trusted?m(home.value):"—"}</strong><span className={(home.profit??0)>=0?"pos":"neg"}>{trusted?m(home.profit)+" · "+p(home.profitPct):"—"}</span></div><div className="qp-return"><button onClick={()=>go("performance")}><small>TWR</small><b>{trusted&&home.twr!=null?p(home.twr*100):"—"}</b><span>результат стратегии</span></button><button onClick={()=>go("income")}><small>ВЫПЛАТЫ</small><b>{trusted?m(income.total):"—"}</b><span>{trusted?m(income.monthly)+" / мес":"факт"}</span></button></div></section>
<section className="qp-history"><header><div><b>Динамика капитала</b><span>стоимость и пополнения · доходность отдельно</span></div><button onClick={()=>go("performance")}>TWR →</button></header><V3HistorySparkline points={trusted?history:[]} detailed/></section>
<section className="qp-split"><article className="qp-allocation"><header><b>Структура</b><button onClick={()=>go("portfolio")}>Все →</button></header><div className="qp-bar">{total>0&&<><i style={{width:classes.stocks/total*100+"%"}}/><i style={{width:classes.bonds/total*100+"%"}}/><i style={{width:classes.other/total*100+"%"}}/></>}</div><div className="qp-legend"><span>Акции <b>{total?Math.round(classes.stocks/total*100):0}%</b></span><span>Облигации <b>{total?Math.round(classes.bonds/total*100):0}%</b></span>{classes.other>0&&<span>Другое <b>{Math.round(classes.other/total*100)}%</b></span>}</div></article><article className="qp-attention"><header><b>Контроль</b></header><button onClick={()=>go("analytics")}><span>Риск и концентрация</span><i>→</i></button><button onClick={()=>go("market")}><span>Рынок и скринер</span><i>→</i></button></article></section>
<section className="qp-holdings"><header><b>Крупнейшие позиции</b><button onClick={()=>go("portfolio")}>Все активы →</button></header>{top.map(x=><button key={x.figi||x.ticker} onClick={()=>go("portfolio")}><span><b>{x.ticker}</b><small>{x.name}</small></span><strong>{m(x.currentValue)}</strong><em className={x.expectedYield>=0?"pos":"neg"}>{x.expectedYield>0?"+":""}{m(x.expectedYield)}</em></button>)}</section></>}
{area==="portfolio"&&<><PageTitle title="Портфель" note={trusted?positions.length+" позиций · "+m(total):"данные не подтверждены"}/><Tabs items={[["assets","Активы"],["operations","Операции"]]} value={portfolioTab} onChange={x=>setPortfolioTab(x as typeof portfolioTab)}/>{trusted?(portfolioTab==="assets"?<CorePortfolioView positions={positions}/>:<Suspense fallback={<Loading/>}><V3OperationsDepth/></Suspense>):<Gate/>}</>}
{area==="performance"&&<><PageTitle title="Результат" note="доходность отдельно от пополнений"/>{trusted?<CorePerformanceView home={home} history={history}/>:<Gate/>}</>}
{area==="income"&&<><PageTitle title="Выплаты" note="факт и будущий денежный поток"/><Tabs items={[["flow","Поток"],["calendar","Календарь"],["history","История"]]} value={incomeTab} onChange={x=>setIncomeTab(x as typeof incomeTab)}/>{trusted?(incomeTab==="flow"?<CoreIncomeCockpit income={income}/>:incomeTab==="calendar"?<CorePayoutCalendar/>:<CoreIncomeHistoryView mode="history"/>):<Gate/>}</>}
{area==="analytics"&&<><PageTitle title="Анализ" note="что происходит · где риск · что изменится"/><Tabs items={[["overview","Сводка"],["risk","Риск"],["structure","Структура"]]} value={analyticsTab} onChange={x=>setAnalyticsTab(x as typeof analyticsTab)}/>{analyticsTab==="overview"?<CoreAnalyticsCockpit positions={positions} history={history} onOpen={x=>setAnalyticsTab(x==="Риск"?"risk":x==="Структура"?"structure":"overview")}/>:trusted?(analyticsTab==="risk"?<CoreRiskView positions={positions} history={history} mode="risk"/>:<CoreStructureView positions={positions}/>):<Gate/>}</>}
{area==="market"&&<><PageTitle title="Рынок" note="контекст MOEX и поиск возможностей"/>{trusted?<CoreMarketView positions={positions} mode="pulse"/>:<Gate/>}</>}
{area==="tools"&&<><PageTitle title="Инструменты" note="read-only лаборатория портфеля"/>{trusted?<><CoreRebalanceView positions={positions}/><Suspense fallback={<Loading/>}><V3AnalysisToolbox positions={positions}/></Suspense></>:<Gate/>}</>}
</main>
<nav className="qp-dock">{NAV.slice(0,5).map(([id,label])=><button key={id} className={area===id?"active":""} onClick={()=>go(id)}><i>{id==="overview"?"⌂":id==="portfolio"?"▦":id==="performance"?"↗":id==="income"?"₽":"⌁"}</i><span>{label}</span></button>)}</nav></div>}
function PageTitle({title,note}:{title:string;note:string}){return <header className="qp-page-title"><h1>{title}</h1><span>{note}</span></header>}
function Tabs({items,value,onChange}:{items:[string,string][];value:string;onChange:(x:string)=>void}){return <nav className="qp-tabs">{items.map(([id,label])=><button key={id} className={value===id?"active":""} onClick={()=>onChange(id)}>{label}</button>)}</nav>}
function Gate(){return <section className="qp-gate"><b>Ждём подтверждённые данные</b><span>QVANIX не подменяет отсутствующие финансовые значения нулями.</span></section>}
function Loading(){return <div className="qp-loading">Открываем модуль…</div>}