import{useEffect,useMemo,useState}from"react";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";import{loadMarketScreener,type MarketScreenerPayload}from"../analysis/marketScreenerApi";import{buildMarketPulse}from"../analysis/marketIntelligenceModel";import{calculateAllocationDrift,type StrategyConfig}from"../../../v2/src/features/analytics/drift";import{calculateRebalanceScenario}from"../../../v2/src/features/analytics/rebalanceScenarios";import"./coreMarketTools.css";
const compact=new Intl.NumberFormat("ru-RU",{notation:"compact",maximumFractionDigits:1}),pct=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1}),rub=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0});
const p=(v:number|null)=>v==null?"—":(v>0?"+":"")+pct.format(v)+"%",money=(v:number)=>rub.format(v)+" ₽";
export function CoreMarketView({positions,mode}:{positions:PositionSnapshot[];mode:"pulse"|"screener"}){
 const[data,setData]=useState<MarketScreenerPayload|null>(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[move,setMove]=useState<"all"|"up"|"down">("all");
 useEffect(()=>{const c=new AbortController();loadMarketScreener(c.signal).then(setData).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[]);
 const pulse=useMemo(()=>buildMarketPulse(data?.rows??[],positions),[data,positions]),portfolio=useMemo(()=>(data?.rows??[]).filter(x=>pulse.portfolioTickers.has(x.secid.toUpperCase())).sort((a,b)=>Math.abs(b.dayChangePct??0)-Math.abs(a.dayChangePct??0)),[data,pulse]),rows=useMemo(()=>(data?.rows??[]).filter(x=>(!query||(x.secid+" "+x.name).toLowerCase().includes(query.toLowerCase()))&&(move==="all"||move==="up"&&(x.dayChangePct??0)>0||move==="down"&&(x.dayChangePct??0)<0)).sort((a,b)=>b.turnoverRub-a.turnoverRub).slice(0,30),[data,query,move]);
 if(loading)return <section className="qmarket qgate">Получаем публичный срез MOEX…</section>;if(!data?.available)return <section className="qmarket qgate">Рыночный срез сейчас не подтверждён источником.</section>;
 return <section className="qmarket"><header><div><span>MOEX · TQBR</span><h2>{mode==="pulse"?"Рынок сегодня":"Скринер"}</h2><small>Наблюдаемые данные · не рейтинг и не торговый сигнал</small></div><b>{data.fetchedAt?new Date(data.fetchedAt).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}):"LIVE"}</b></header>
 {mode==="pulse"?<><div className="qm-metrics"><article><span>Рост / падение</span><strong>{pulse.gainers} / {pulse.losers}</strong></article><article><span>Оборот</span><strong>{compact.format(pulse.turnover)} ₽</strong></article><article><span>Лидер оборота</span><strong>{pulse.topTurnover?.secid??"—"}</strong></article><article><span>Мои бумаги</span><strong>{pulse.portfolioMatches}</strong></article></div><h3>Портфель × рынок</h3><div className="qm-rows">{portfolio.map(x=><article key={x.secid}><div><b>{x.secid}</b><span>{x.name}</span></div><strong className={(x.dayChangePct??0)>0?"pos":(x.dayChangePct??0)<0?"neg":""}>{p(x.dayChangePct)}</strong><small>{compact.format(x.turnoverRub)} ₽</small></article>)}</div></>:<><div className="qm-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Тикер или название"/>{(["all","up","down"]as const).map(x=><button className={move===x?"active":""} onClick={()=>setMove(x)} key={x}>{x==="all"?"Все":x==="up"?"Рост":"Падение"}</button>)}</div><div className="qm-rows">{rows.map(x=><article key={x.secid}><div><b>{x.secid}</b><span>{x.name}</span></div><strong className={(x.dayChangePct??0)>0?"pos":(x.dayChangePct??0)<0?"neg":""}>{p(x.dayChangePct)}</strong><small>{compact.format(x.turnoverRub)} ₽</small></article>)}</div></>}
 <footer>Текущий публичный рыночный срез описывает состояние рынка в момент загрузки и не прогнозирует дальнейшее движение.</footer></section>}
export function CoreRebalanceView({positions}:{positions:PositionSnapshot[]}){
 const[target,setTarget]=useState("50"),[flow,setFlow]=useState(""),equity=Number(target.replace(",",".")),ready=Number.isFinite(equity)&&equity>0&&equity<100,strategy=useMemo<StrategyConfig|null>(()=>ready?{version:"1.0",name:"Пользовательская цель",targets:[{key:"equity",label:"Акции",target:equity/100},{key:"bond",label:"Облигации",target:(100-equity)/100}],absoluteTolerance:.05,relativeTolerance:.2}:null,[equity,ready]),drift=useMemo(()=>strategy?calculateAllocationDrift(positions,strategy):null,[positions,strategy]),amount=Number(flow.replace(",",".")),scenario=useMemo(()=>drift&&amount>0?calculateRebalanceScenario(drift,"ADD_CAPITAL",amount):null,[drift,amount]);
 return <section className="qtool"><header><div><span>WHAT IF · READ ONLY</span><h2>Ребалансировка</h2><small>Вы задаёте цель и сумму. QVANIX показывает только дельту классов.</small></div></header><div className="qt-controls"><label>Акции, %<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><div><span>Облигации</span><strong>{ready?pct.format(100-equity)+"%":"—"}</strong></div><label>Новое пополнение, ₽<input inputMode="decimal" value={flow} onChange={e=>setFlow(e.target.value)} placeholder="например, 12000"/></label></div>
 {drift?.available&&<div className="qt-drift">{drift.rows.map(r=><article key={r.key}><div><b>{r.label}</b><span>{pct.format(r.actual*100)}% → {pct.format(r.target*100)}%</span></div><i><b style={{width:Math.min(100,r.actual*100)+"%"}}/><em style={{left:Math.min(100,r.target*100)+"%"}}/></i><strong>{(r.delta>0?"+":"")+pct.format(r.delta*100)} п.п.</strong></article>)}</div>}
 {scenario?.available?<div className="qt-result"><header><span>Сценарий после пополнения</span><strong>{scenario.assignedValueAfter==null?"—":money(scenario.assignedValueAfter)}</strong></header>{scenario.rows.map(r=><article key={r.key}><span>{r.label}</span><b className={r.deltaValue>=0?"pos":"neg"}>{r.deltaValue>0?"+":""}{money(r.deltaValue)}</b></article>)}</div>:<p className="qt-hint">{!ready?"Введите цель от 1% до 99%.":"Введите сумму пополнения — расчёт появится сразу."}</p>}<footer>Без заявок и выбора конкретных бумаг. Комиссии, налоги, спреды и лоты не моделируются.</footer></section>}