import type{HistoryPoint}from"../../../v2/src/lib/portfolioApi";import{buildResultEvidenceV120}from"./resultReconciliationModelV120";import"./coreResultReconciliationV120.css";
const rub=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0,signDisplay:"exceptZero"}),pct=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0});
const money=(v:number)=>rub.format(v)+" ₽";const date=(v:string|null)=>v?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v+"T00:00:00Z")):"—";
export function CoreResultReconciliationV120({totalResult,openPositionPl,realizedPayouts,trusted,history}:{totalResult:number|null;openPositionPl:number|null;realizedPayouts:number|null;trusted:boolean;history:HistoryPoint[]}){
 const m=buildResultEvidenceV120({totalResult,openPositionPl,realizedPayouts,trusted,history});if(!m)return null;
 const facts=[["Общий результат",m.totalResult,"стоимость минус чистые внешние денежные потоки"],["Открытый P/L",m.openPositionPl,"брокерский P/L только текущих позиций"],["Полученные выплаты",m.realizedPayouts,"подтверждённые купоны и дивиденды"]] as const;
 return <section className="sb-result-reconcile-v120" aria-label="Карта доказательств результата"><header><div><span>КАРТА РЕЗУЛЬТАТА</span><strong>Три факта — три разных вопроса</strong></div><small>FACT · read-only</small></header>
 <div className="sb-result-reconcile-v120__facts" aria-label="Независимые факты результата">{facts.map(([label,value,note])=><article key={label}><span>{label}</span><strong className={value>0?"up":value<0?"down":""}>{money(value)}</strong><small>{note}</small></article>)}</div>
 <aside><b>Почему QVANIX не складывает эти числа</b><p>Они пересекаются по экономическому смыслу и не образуют подтверждённую аддитивную атрибуцию. Без отдельного журнала закрытых сделок, комиссий и налогов система не вычисляет «остаток» и не выдаёт его за факт.</p></aside>
 <div className="sb-result-reconcile-v120__evidence" aria-label="Покрытие доказательствами"><article><span>История стоимости</span><strong>{m.valuePoints} / {m.historyPoints}</strong><small>точек с подтверждённой стоимостью</small></article><article><span>Общий отрезок с IMOEX</span><strong>{m.benchmarkCommonPoints}</strong><small>{m.benchmarkCoveragePct==null?"нет истории":pct.format(m.benchmarkCoveragePct)+"% доступных точек"}</small></article><article><span>Границы истории</span><strong>{date(m.startDate)}</strong><small>до {date(m.endDate)}</small></article></div>
 <footer>Сравнение с IMOEX строится только на общих подтверждённых точках. Карта описывает доступность доказательств и наблюдаемые факты, а не прогноз, рекомендацию или причинную атрибуцию доходности.</footer></section>;
}
