import{useEffect,useMemo,useState}from"react";
import{createPortal}from"react-dom";
import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";
import{loadMarketScreener,type MarketScreenerPayload,type MarketScreenerRow}from"../analysis/marketScreenerApi";

const one=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1,signDisplay:"exceptZero"});
const plain=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1});
const compact=new Intl.NumberFormat("ru-RU",{notation:"compact",maximumFractionDigits:1});
const money=(value:number)=>compact.format(value)+" ₽";
const pct=(value:number|null)=>value==null?"—":one.format(value)+"%";
const finite=(value:number|null|undefined)=>Number.isFinite(value)?Number(value):0;
const median=(values:number[])=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2};

function CenterRail({value,maxAbs}:{value:number;maxAbs:number}){const width=Math.min(100,Math.abs(value)/Math.max(.01,maxAbs)*100);return <div className="qv116-center-rail"><i/><span className={value<0?"neg":""} style={{width:(value<0?width:0)+"%"}}/><b className={value>0?"pos":""} style={{width:(value>0?width:0)+"%"}}/></div>}

function MarketCommand({data,positions}:{data:MarketScreenerPayload;positions:PositionSnapshot[]}){
 const rows=data.rows;
 const moveRows=useMemo(()=>rows.filter(row=>row.dayChangePct!=null),[rows]);
 const turnoverTotal=rows.reduce((sum,row)=>sum+row.turnoverRub,0),sortedTurnover=[...rows].sort((a,b)=>b.turnoverRub-a.turnoverRub),top1Share=turnoverTotal?sortedTurnover.slice(0,1).reduce((s,r)=>s+r.turnoverRub,0)/turnoverTotal*100:0,top3Share=turnoverTotal?sortedTurnover.slice(0,3).reduce((s,r)=>s+r.turnoverRub,0)/turnoverTotal*100:0,top5Share=turnoverTotal?sortedTurnover.slice(0,5).reduce((s,r)=>s+r.turnoverRub,0)/turnoverTotal*100:0;
 const up=moveRows.filter(row=>(row.dayChangePct??0)>0),down=moveRows.filter(row=>(row.dayChangePct??0)<0),flat=moveRows.length-up.length-down.length,medianMove=median(moveRows.map(row=>row.dayChangePct??0)),medianRange=median(rows.filter(row=>row.rangePct!=null).map(row=>row.rangePct??0));
 const buckets=[{key:"hard-down",label:"≤ −2%",count:moveRows.filter(r=>(r.dayChangePct??0)<=-2).length},{key:"down",label:"−2…0%",count:moveRows.filter(r=>(r.dayChangePct??0)>-2&&(r.dayChangePct??0)<0).length},{key:"flat",label:"0%",count:flat},{key:"up",label:"0…2%",count:moveRows.filter(r=>(r.dayChangePct??0)>0&&(r.dayChangePct??0)<2).length},{key:"hard-up",label:"≥ +2%",count:moveRows.filter(r=>(r.dayChangePct??0)>=2).length}];
 const maxAbsMove=Math.max(.1,...moveRows.map(row=>Math.abs(row.dayChangePct??0))),leaders=[...moveRows].sort((a,b)=>Math.abs(b.dayChangePct??0)-Math.abs(a.dayChangePct??0)).slice(0,8),rangeRows=[...rows].filter(row=>row.rangePct!=null).sort((a,b)=>(b.rangePct??0)-(a.rangePct??0)).slice(0,6),maxRange=Math.max(.1,...rangeRows.map(row=>row.rangePct??0));
 const positionMap=new Map(positions.map(position=>[position.ticker.toUpperCase(),position] as const)),portfolioTotal=positions.reduce((sum,row)=>sum+Math.max(0,finite(row.currentValue)),0),matched=rows.map(row=>({row,position:positionMap.get(row.secid.toUpperCase())})).filter((item):item is{row:MarketScreenerRow;position:PositionSnapshot}=>Boolean(item.position)).sort((a,b)=>finite(b.position.currentValue)-finite(a.position.currentValue)),matchedCapital=matched.reduce((sum,item)=>sum+Math.max(0,finite(item.position.currentValue)),0),coverage=portfolioTotal?matchedCapital/portfolioTotal*100:null,matchedWithMove=matched.filter(item=>item.row.dayChangePct!=null),moveCapital=matchedWithMove.reduce((sum,item)=>sum+Math.max(0,finite(item.position.currentValue)),0),weightedMove=moveCapital?matchedWithMove.reduce((sum,item)=>sum+Math.max(0,finite(item.position.currentValue))*(item.row.dayChangePct??0),0)/moveCapital:null,posCapital=matchedWithMove.filter(item=>(item.row.dayChangePct??0)>0).reduce((sum,item)=>sum+Math.max(0,finite(item.position.currentValue)),0),negCapital=matchedWithMove.filter(item=>(item.row.dayChangePct??0)<0).reduce((sum,item)=>sum+Math.max(0,finite(item.position.currentValue)),0),flatCapital=Math.max(0,moveCapital-posCapital-negCapital),fresh=data.fetchedAt?new Intl.DateTimeFormat("ru-RU",{hour:"2-digit",minute:"2-digit"}).format(new Date(data.fetchedAt)):"—";
 return <section className="qv116" aria-label="Market command center">
  <header className="qv116-head"><div><span>MARKET COMMAND CENTER · V116</span><h2>Рыночный срез без декоративного шума</h2><p>Ширина рынка, ликвидность и пересечение с текущим портфелем — только по подтверждённому TQBR-срезу.</p></div><aside><b>{data.board||"TQBR"}</b><small>{data.source||"MOEX"} · {fresh}</small></aside></header>
  <div className="qv116-kpis"><article><span>Растут / падают</span><b>{up.length} / {down.length}</b><small>{moveRows.length?plain.format(up.length/moveRows.length*100):"—"}% наблюдаемого среза растёт</small></article><article><span>Медиана движения</span><b className={(medianMove??0)>0?"up":(medianMove??0)<0?"down":""}>{pct(medianMove)}</b><small>по бумагам с подтверждённым изменением</small></article><article><span>Топ-5 оборота</span><b>{plain.format(top5Share)}%</b><small>концентрация оборота текущего среза</small></article><article><span>Покрытие портфеля</span><b>{coverage==null?"—":plain.format(coverage)+"%"}</b><small>{matched.length} точных совпадений тикеров</small></article></div>
  <section className="qv116-panel qv116-breadth"><header><b>Ширина рынка</b><span>распределение дневного движения</span></header><div className="qv116-breadth__rail">{buckets.map(bucket=><i key={bucket.key} className={bucket.key} style={{width:(moveRows.length?bucket.count/moveRows.length*100:0)+"%"}} title={`${bucket.label}: ${bucket.count}`}/>)}</div><div className="qv116-breadth__legend">{buckets.map(bucket=><div key={bucket.key}><span>{bucket.label}</span><b>{bucket.count}</b></div>)}</div><div className="qv116-move-list">{leaders.map(row=><div key={row.secid}><span><b>{row.secid}</b><small>{row.name}</small></span><CenterRail value={row.dayChangePct??0} maxAbs={maxAbsMove}/><strong className={(row.dayChangePct??0)>0?"up":(row.dayChangePct??0)<0?"down":""}>{pct(row.dayChangePct)}</strong></div>)}</div></section>
  <div className="qv116-grid"><section className="qv116-panel"><header><b>Концентрация оборота</b><span>единая шкала</span></header><div className="qv116-turnover-kpis"><article><span>Топ-1</span><b>{plain.format(top1Share)}%</b></article><article><span>Топ-3</span><b>{plain.format(top3Share)}%</b></article><article><span>Топ-5</span><b>{plain.format(top5Share)}%</b></article></div><div className="qv116-bars">{sortedTurnover.slice(0,7).map(row=><div key={row.secid}><span>{row.secid}</span><i><b style={{width:(sortedTurnover[0]?.turnoverRub?row.turnoverRub/sortedTurnover[0].turnoverRub*100:0)+"%"}}/></i><strong>{money(row.turnoverRub)}</strong></div>)}</div></section><section className="qv116-panel"><header><b>Внутридневной диапазон</b><span>high–low / last</span></header><div className="qv116-bars">{rangeRows.map(row=><div key={row.secid}><span>{row.secid}</span><i><b style={{width:Math.max(2,(row.rangePct??0)/maxRange*100)+"%"}}/></i><strong>{pct(row.rangePct)}</strong></div>)}</div><footer>Медиана диапазона: {medianRange==null?"—":plain.format(medianRange)+"%"}. Это мера наблюдаемого внутридневного разброса, не прогноз волатильности.</footer></section></div>
  <section className="qv116-panel qv116-portfolio"><header><div><b>Портфель × рынок</b><span>только точные совпадения тикеров TQBR</span></div><strong>{coverage==null?"—":plain.format(coverage)+"% капитала"}</strong></header><div className="qv116-portfolio__kpis"><article><span>Наблюдаемое взвешенное движение</span><b className={(weightedMove??0)>0?"up":(weightedMove??0)<0?"down":""}>{pct(weightedMove)}</b><small>не доходность портфеля; только текущие TQBR-движения совпавших позиций</small></article><article><span>Капитал в растущих</span><b>{moveCapital?plain.format(posCapital/moveCapital*100)+"%":"—"}</b><small>из покрытого капиталом TQBR-среза</small></article><article><span>Капитал в падающих</span><b>{moveCapital?plain.format(negCapital/moveCapital*100)+"%":"—"}</b><small>из покрытого капиталом TQBR-среза</small></article></div><div className="qv116-capital-rail"><i className="up" style={{width:(moveCapital?posCapital/moveCapital*100:0)+"%"}}/><i className="flat" style={{width:(moveCapital?flatCapital/moveCapital*100:0)+"%"}}/><i className="down" style={{width:(moveCapital?negCapital/moveCapital*100:0)+"%"}}/></div><div className="qv116-portfolio__table"><header><span>Бумага</span><span>Вес</span><span>День</span><span>Оборот</span></header>{matched.slice(0,10).map(({row,position})=><div key={row.secid}><span><b>{row.secid}</b><small>{position.name}</small></span><strong>{portfolioTotal?plain.format(finite(position.currentValue)/portfolioTotal*100)+"%":"—"}</strong><em className={(row.dayChangePct??0)>0?"up":(row.dayChangePct??0)<0?"down":""}>{pct(row.dayChangePct)}</em><span>{money(row.turnoverRub)}</span></div>)}</div>{positions.length>matched.length&&<p className="qv116-note">Не совпало с TQBR: {positions.filter(position=>!rows.some(row=>row.secid.toUpperCase()===position.ticker.toUpperCase())).slice(0,8).map(position=>position.ticker).join(" · ")||"—"}. Такие позиции не исчезли из портфеля — они просто не входят в подтверждённый TQBR-срез.</p>}</section>
  <footer className="qv116-note">Все показатели описывают только текущий подтверждённый рыночный срез. Они не являются прогнозом, торговым сигналом или рекомендацией.</footer>
 </section>;
}

export function CoreMarketCommandCenterV116({positions}:{positions:PositionSnapshot[]}){
 const[host,setHost]=useState<HTMLElement|null>(null),[data,setData]=useState<MarketScreenerPayload|null>(null);
 useEffect(()=>{let currentHost:HTMLElement|null=null,currentLegacy:HTMLElement|null=null;const detach=()=>{if(currentLegacy)delete currentLegacy.dataset.qv116Replaced;if(currentHost?.isConnected)currentHost.remove();currentHost=null;currentLegacy=null};const attach=()=>{const metrics=document.querySelector<HTMLElement>(".v3-market-pulse__metrics");if(!metrics){if(currentHost)detach();setHost(null);return}if(currentHost&&currentHost.isConnected)return;detach();const next=document.createElement("div");next.className="qv116-host";metrics.insertAdjacentElement("afterend",next);currentHost=next;currentLegacy=metrics.parentElement?.querySelector<HTMLElement>(".v3-market-portfolio")??null;if(currentLegacy)currentLegacy.dataset.qv116Replaced="true";setHost(next)};attach();const observer=new MutationObserver(attach);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();detach()}},[]);
 useEffect(()=>{if(!host)return;const controller=new AbortController();void loadMarketScreener(controller.signal).then(next=>{if(!controller.signal.aborted)setData(next)}).catch(()=>{});return()=>controller.abort()},[host]);
 if(!host)return null;if(!data?.available)return createPortal(<div className="qv116-loading"><b>Собираем визуальный рыночный срез…</b><small>QVANIX ждёт подтверждённые строки MOEX.</small></div>,host);return createPortal(<MarketCommand data={data} positions={positions}/>,host);
}
