import type{V3HistoryWindow}from"../history/historyLens";
export type CoreTab="home"|"portfolio"|"result"|"income"|"more";
export type CoreWorkspaceState={tab:CoreTab;portfolioMode:"assets"|"structure"|"compare"|"map"|"depth";incomeMode:"overview"|"calendar"|"depth";hub:"analytics"|"market"|"tools";analyticsMode:"concentration"|"breadth"|"risk"|"depth";resultWindow:V3HistoryWindow;resultChartMode:"value"|"performance"};
const KEY="qvanix-core-workspace-state-v214",LEGACY_KEY="qvanix-core-workspace-state-v213";
export const CORE_WORKSPACE_DEFAULTS:CoreWorkspaceState={tab:"home",portfolioMode:"assets",incomeMode:"overview",hub:"analytics",analyticsMode:"concentration",resultWindow:"all",resultChartMode:"value"};
const allowed={tab:new Set(["home","portfolio","result","income","more"]),portfolioMode:new Set(["assets","structure","compare","map","depth"]),incomeMode:new Set(["overview","calendar","depth"]),hub:new Set(["analytics","market","tools"]),analyticsMode:new Set(["concentration","breadth","risk","depth"]),resultWindow:new Set(["7d","30d","90d","180d","ytd","365d","5y","all"]),resultChartMode:new Set(["value","performance"])} as const;
export function readCoreWorkspaceState():CoreWorkspaceState{try{const raw=JSON.parse(sessionStorage.getItem(KEY)||sessionStorage.getItem(LEGACY_KEY)||"{}") as Partial<CoreWorkspaceState>;return{tab:allowed.tab.has(raw.tab as any)?raw.tab!:CORE_WORKSPACE_DEFAULTS.tab,portfolioMode:allowed.portfolioMode.has(raw.portfolioMode as any)?raw.portfolioMode!:CORE_WORKSPACE_DEFAULTS.portfolioMode,incomeMode:allowed.incomeMode.has(raw.incomeMode as any)?raw.incomeMode!:CORE_WORKSPACE_DEFAULTS.incomeMode,hub:allowed.hub.has(raw.hub as any)?raw.hub!:CORE_WORKSPACE_DEFAULTS.hub,analyticsMode:allowed.analyticsMode.has(raw.analyticsMode as any)?raw.analyticsMode!:CORE_WORKSPACE_DEFAULTS.analyticsMode,resultWindow:allowed.resultWindow.has(raw.resultWindow as any)?raw.resultWindow!:CORE_WORKSPACE_DEFAULTS.resultWindow,resultChartMode:allowed.resultChartMode.has(raw.resultChartMode as any)?raw.resultChartMode!:CORE_WORKSPACE_DEFAULTS.resultChartMode}}catch{return CORE_WORKSPACE_DEFAULTS}}
export function writeCoreWorkspaceState(value:CoreWorkspaceState){try{sessionStorage.setItem(KEY,JSON.stringify(value))}catch{}}
const SCROLL_KEY="qvanix-core-scroll-v214";
export function readCoreScroll(tab:CoreTab){try{const raw=JSON.parse(sessionStorage.getItem(SCROLL_KEY)||"{}") as Partial<Record<CoreTab,number>>;const y=raw[tab];return typeof y==="number"&&Number.isFinite(y)&&y>=0?y:0}catch{return 0}}
export function writeCoreScroll(tab:CoreTab,y:number){try{const raw=JSON.parse(sessionStorage.getItem(SCROLL_KEY)||"{}") as Partial<Record<CoreTab,number>>;raw[tab]=Math.max(0,Math.round(y));sessionStorage.setItem(SCROLL_KEY,JSON.stringify(raw))}catch{}}
