import{useEffect,useMemo,useState}from"react";import{loadPayoutCalendar,type PayoutCalendar,type PayoutEvent}from"../../../v2/src/lib/payoutsApi";import"./corePayoutCalendar.css";
const money=(v:number|null|undefined)=>typeof v==="number"&&Number.isFinite(v)?new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0}).format(v)+" ₽":"—";
const monthFmt=new Intl.DateTimeFormat("ru-RU",{month:"short",year:"numeric",timeZone:"UTC"}),dayFmt=new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",timeZone:"UTC"});
const monthLabel=(k:string)=>monthFmt.format(new Date(k+"-01T00:00:00Z"));const kind=(e:PayoutEvent)=>String(e.kind).toUpperCase()==="COUPON"?"Купон":"Дивиденд";
export function CorePayoutCalendar(){const[data,setData]=useState<PayoutCalendar|null>(null),[loading,setLoading]=useState(true),[selected,setSelected]=useState<string|null>(null);useEffect(()=>{let on=true;loadPayoutCalendar().then(x=>{if(on){setData(x);setSelected(x.months.find(m=>m.count>0)?.key??null);setLoading(false)}});return()=>{on=false}},[]);
 const months=useMemo(()=>data?.months.filter(m=>m.count>0)??[],[data]),active=months.find(m=>m.key===selected)??months[0],events=(active?.items??[]).filter(e=>e.status!=="FACT").sort((a,b)=>a.date.localeCompare(b.date));
 if(loading)return <section className="qpay"><p>Загружаем календарь выплат…</p></section>;if(!data?.available)return <section className="qpay"><header><div><span>CASH FLOW</span><h2>Календарь выплат</h2></div></header><p>Подтверждённое расписание сейчас недоступно. Значения не подменяются оценкой.</p></section>;
 return <section className="qpay"><header><div><span>12M CASH FLOW</span><h2>Календарь выплат</h2><small>Будущие купоны и дивиденды · отдельно от фактически полученного дохода</small></div><div><b>{money(data.forecast.gross)}</b><small>{data.forecast.count} событий</small></div></header>
 <div className="qpay-months">{months.map(m=><button key={m.key} className={active?.key===m.key?"active":""} onClick={()=>setSelected(m.key)}><span>{monthLabel(m.key)}</span><strong>{money(m.gross)}</strong><small>{m.count} выплат</small></button>)}</div>
 {active&&<><div className="qpay-summary"><div><span>{monthLabel(active.key)}</span><strong>{money(active.gross)}</strong></div><div><span>Событий</span><strong>{active.count}</strong></div><div><span>Покрытие</span><strong>{Math.round(data.coverage.coverageRatio*100)}%</strong></div></div><div className="qpay-events">{events.slice(0,12).map((e,i)=><article key={(e.scheduleId||e.figi||e.ticker)+e.date+i}><time>{dayFmt.format(new Date(e.date))}</time><div><b>{e.ticker}</b><span>{e.name}</span></div><em>{kind(e)}</em><strong>{money(e.gross)}</strong></article>)}{events.length===0&&<p>В этом месяце нет подтверждённых будущих выплат.</p>}</div>{events.length>12&&<p className="qpay-more">Ещё {events.length-12} событий скрыты — месячная сводка остаётся компактной.</p>}</>}
 <footer><span>FACT</span> не смешивается с расписанием. Будущие суммы — gross и не являются гарантией выплаты.{data.stale?" Источник помечен как устаревший.":""}</footer></section>}