import{useMemo,useState}from"react";import type{HistoryPoint,PositionSnapshot}from"../../../v2/src/lib/portfolioApi";import type{V3HomeViewModel}from"../home/homeViewModel";import type{V3IncomeModel}from"../income/V3Income";import{V3HistorySparkline}from"../home/V3HistorySparkline";import{CorePayoutCalendar}from"./CorePayoutCalendar";import"./snowballCore.css";
type Tab="home"|"portfolio"|"result"|"income"|"more";const rub=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0}),dec=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1,signDisplay:"exceptZero"}),money=(v:number|null)=>v==null?"—":rub.format(v)+" ₽",pct=(v:number|null)=>v==null?"—":dec.format(v)+"%";
export function SnowballCore({home,positions,history,income,connection}:{home:V3HomeViewModel;positions:PositionSnapshot[];history:HistoryPoint[];income:V3IncomeModel;connection:{state:string;reason:string|null;refresh:()=>Promise<void>;refreshing:boolean}}){const[tab,setTab]=useState<Tab>("home"),[portfolioMode,setPortfolioMode]=useState<"assets"|"structure">("assets"),[incomeMode,setIncomeMode]=useState<"overview"|"calendar">("overview"),trusted=home.isTrusted,total=positions.reduce((s,x)=>s+x.currentValue,0),profit=positions.reduce((s,x)=>s+x.expectedYield,0),sorted=useMemo(()=>[...positions].sort((a,b)=>b.currentValue-a.currentValue),[positions]),groups=useMemo(()=>{const r=[{key:"Акции",v:0},{key:"Облигации",v:0},{key:"Другое",v:0}];for(const x of positions){const t=(x.instrumentType||"").toLowerCase();(t.includes("bond")?r[1]:t.includes("share")||t.includes("stock")?r[0]:r[2]).v+=x.currentValue}return r.filter(x=>x.v>0)},[positions]);const go=(x:Tab)=>{setTab(x);window.scrollTo({top:0,behavior:"smooth"})};return <div className="sb">
<header className="sb-top"><button onClick={()=>go("home")}><i>Q</i><span><b>QVANIX</b><small>{home.accountName||"Портфель"}</small></span></button><button className={trusted?"live":""} onClick={()=>void connection.refresh()}><i/>{trusted?"Данные обновлены":"Обновить"}</button></header>
{!trusted&&<aside className="sb-alert"><b>{connection.state==="loading"?"Загружаем портфель":"Нет подтверждённых данных"}</b><span>{connection.reason??"Показатели появятся после подтверждения источника."}</span></aside>}
<main>
{tab==="home"&&<><section className="sb-balance"><span>Стоимость портфеля</span><strong>{trusted?money(home.value):"—"}</strong><b className={(home.profit??0)>=0?"up":"down"}>{trusted?money(home.profit)+" · "+pct(home.profitPct):"—"}</b><div><button onClick={()=>go("result")}><span>Доходность TWR</span><b>{trusted&&home.twr!=null?pct(home.twr*100):"—"}</b></button><button onClick={()=>go("income")}><span>Получено выплат</span><b>{trusted?money(income.total):"—"}</b></button></div></section>
<section className="sb-chart"><header><b>История портфеля</b><button onClick={()=>go("result")}>Подробнее</button></header><V3HistorySparkline points={trusted?history:[]} detailed/></section>
<section className="sb-block"><header><b>Состав портфеля</b><button onClick={()=>go("portfolio")}>Все активы</button></header><div className="sb-allocation">{groups.map((x,i)=><div key={x.key}><i className={"c"+i} style={{width:(total?x.v/total*100:0)+"%"}}/><span>{x.key}</span><b>{total?Math.round(x.v/total*100):0}%</b></div>)}</div></section>
<section className="sb-block sb-list"><header><b>Активы</b><span>{positions.length} позиций</span></header>{sorted.slice(0,5).map(x=><AssetRow key={x.figi||x.ticker} x={x} total={total}/>)}</section>
<section className="sb-block sb-actions"><header><b>Быстрый доступ</b></header><button onClick={()=>go("income")}><span>Календарь выплат</span><b>→</b></button><button onClick={()=>go("more")}><span>Аналитика и рынок</span><b>→</b></button></section></>}
{tab==="portfolio"&&<><Title title="Портфель" note={trusted?money(total)+" · "+positions.length+" позиций":"нет данных"}/><Switch value={portfolioMode} onChange={setPortfolioMode} items={[["assets","Активы"],["structure","Структура"]]}/>{portfolioMode==="assets"?<section className="sb-block sb-list sb-full">{sorted.map(x=><AssetRow key={x.figi||x.ticker} x={x} total={total}/>)}</section>:<section className="sb-block"><div className="sb-structure">{groups.map((x,i)=><article key={x.key}><span><i className={"dot c"+i}/>{x.key}</span><b>{money(x.v)}</b><strong>{total?dec.format(x.v/total*100):0}%</strong><div><i className={"c"+i} style={{width:(total?x.v/total*100:0)+"%"}}/></div></article>)}</div></section>}</>}
{tab==="result"&&<><Title title="Результат" note="без смешивания доходности и пополнений"/><section className="sb-result-head"><article><span>TWR</span><strong>{trusted&&home.twr!=null?pct(home.twr*100):"—"}</strong><small>доходность стратегии</small></article><article><span>XIRR</span><strong>{trusted&&home.xirr!=null?pct(home.xirr*100):"—"}</strong><small>с учётом потоков</small></article><article><span>CAGR</span><strong>{trusted&&home.cagr!=null?pct(home.cagr*100):"—"}</strong><small>годовой темп</small></article></section><section className="sb-chart sb-result-chart"><header><b>Портфель и пополнения</b></header><V3HistorySparkline points={trusted?history:[]} detailed/></section><section className="sb-block sb-summary"><div><span>Текущий P/L позиций</span><b className={profit>=0?"up":"down"}>{trusted?money(profit):"—"}</b></div><div><span>Начало истории</span><b>{home.startDate??"—"}</b></div></section></>}
{tab==="income"&&<><Title title="Выплаты" note="получено отдельно от будущего расписания"/><Switch value={incomeMode} onChange={setIncomeMode} items={[["overview","Обзор"],["calendar","Календарь"]]}/>{incomeMode==="overview"?<><section className="sb-income-head"><article><span>Получено</span><strong>{trusted?money(income.total):"—"}</strong><small>факт · net</small></article><article><span>Средний месяц</span><strong>{trusted?money(income.monthly):"—"}</strong><small>по доступной истории</small></article></section><section className="sb-block sb-income-road"><div><span>Факт</span><b>{trusted?money(income.total):"—"}</b></div><i>→</i><div><span>Средний месяц</span><b>{trusted?money(income.monthly):"—"}</b></div><i>→</i><div><span>12М эквивалент</span><b>{trusted?money(income.annual):"—"}</b></div></section><section className="sb-note">12М эквивалент — масштаб наблюдаемого среднего, а не прогноз будущих выплат.</section></>:<CorePayoutCalendar/>}</>}
{tab==="more"&&<><Title title="Разделы" note="аналитика QVANIX поверх портфельного ядра"/><section className="sb-menu"><button><i>◎</i><span><b>Аналитика</b><small>риск, структура, корреляция, сценарии</small></span><em>→</em></button><button><i>⌁</i><span><b>Рынок</b><small>MOEX, скринер, просадки, дивиденды</small></span><em>→</em></button><button><i>◇</i><span><b>Инструменты</b><small>ребалансировка, Portfolio Lab, отчёты</small></span><em>→</em></button></section></>}
</main><nav className="sb-nav">{([["home","Обзор","⌂"],["portfolio","Портфель","▦"],["result","Результат","↗"],["income","Выплаты","₽"],["more","Разделы","•••"]]as [Tab,string,string][]).map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>go(id)}><i>{icon}</i><span>{label}</span></button>)}</nav></div>}
function AssetRow({x,total}:{x:PositionSnapshot;total:number}){const w=total?x.currentValue/total*100:0;return <button className="sb-asset"><span><b>{x.ticker}</b><small>{x.name}</small></span><em>{dec.format(w)}%</em><strong>{money(x.currentValue)}<small className={x.expectedYield>=0?"up":"down"}>{x.expectedYield>0?"+":""}{money(x.expectedYield)}</small></strong></button>}
function Title({title,note}:{title:string;note:string}){return <header className="sb-title"><h1>{title}</h1><span>{note}</span></header>}
function Switch<T extends string>({value,onChange,items}:{value:T;onChange:(x:T)=>void;items:[T,string][]}){return <nav className="sb-switch">{items.map(([id,label])=><button className={value===id?"active":""} onClick={()=>onChange(id)} key={id}>{label}</button>)}</nav>}