import{useEffect,useState,type ReactNode}from"react";
const KEY="qvanix.v3.demoTourSeen";
const STEPS=[
{eyebrow:"01 · ПУЛЬТ",title:"Сначала — ответ, потом глубина",body:"На первом экране видны капитал, TWR, денежный результат и поток. TWR — основная доходность для сравнения с рынком; XIRR показывает личный результат с учётом дат пополнений."},
{eyebrow:"02 · ПОРТФЕЛЬ",title:"От общего к конкретному активу",body:"Откройте «Портфель», затем любую позицию. QVANIX использует одну каноническую карточку актива: состав, история, риск и подтверждённые данные без дублирующих экранов."},
{eyebrow:"03 · АНАЛИТИКА",title:"Риск объясняется, а не прячется",body:"В «Аналитике» собраны benchmark, концентрация и риск. Сложные метрики раскрываются через контекстную помощь; неподтверждённые данные не превращаются в нули."},
{eyebrow:"04 · ДОХОД И ЦЕЛЬ",title:"Долгий горизонт вместо торгового шума",body:"«Доход» показывает денежный поток, а «Цель» — сценарии долгосрочного движения. Сценарий не является прогнозом или обещанием результата."}
]as const;
export function V3DemoGuide({children}:{children:ReactNode}){const[open,setOpen]=useState(()=>{try{return localStorage.getItem(KEY)!=="1"}catch{return true}}),[step,setStep]=useState(0);useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="ArrowRight")setStep(v=>Math.min(STEPS.length-1,v+1));if(event.key==="ArrowLeft")setStep(v=>Math.max(0,v-1))};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open]);const close=()=>{try{localStorage.setItem(KEY,"1")}catch{}setOpen(false)};const restart=()=>{setStep(0);setOpen(true)};const current=STEPS[step];return <div className="v3-demo-root">{children}<button className="v3-demo-tour-trigger" type="button" onClick={restart} aria-label="Открыть экскурсию по демо">Экскурсия</button>{open&&<div className="v3-demo-tour" role="dialog" aria-modal="true" aria-labelledby="v3-demo-tour-title"><button className="v3-demo-tour-scrim" aria-label="Закрыть экскурсию" onClick={close}/><section><div className="v3-demo-tour-head"><span>{current.eyebrow}</span><button type="button" onClick={close} aria-label="Закрыть">×</button></div><h1 id="v3-demo-tour-title">{current.title}</h1><p>{current.body}</p><div className="v3-demo-tour-dots" aria-label={`Шаг ${step+1} из ${STEPS.length}`}>{STEPS.map((_,i)=><i key={i} className={i===step?"is-active":""}/>)}</div><footer><button type="button" className="is-secondary" onClick={close}>Смотреть самому</button>{step>0&&<button type="button" className="is-secondary" onClick={()=>setStep(v=>v-1)}>Назад</button>}<button type="button" className="is-primary" onClick={()=>step===STEPS.length-1?close():setStep(v=>v+1)}>{step===STEPS.length-1?"В демо":"Дальше"}</button></footer><small>Демо использует только синтетические данные. Никакого брокерского подключения или реальных финансовых значений.</small></section></div>}</div>}
