import{useEffect,useMemo,useState}from"react";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";import{loadAssetHistory,type AssetHistorySeries}from"../../../v2/src/lib/assetHistoryApi";import type{V3DetailMode,V3Shell}from"../app/model";import{V3HistoryWindowControl}from"../history/V3HistoryWindowControl";import type{V3HistoryWindow}from"../history/historyLens";import{filterAssetHistoryWindow,summarizeAssetHistory}from"./assetHistoryLens";

type View="overview"|"history"|"position";
const rub=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0}),priceFmt=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}),pct=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1,signDisplay:"exceptZero"}),plainPct=new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1}),dateFmt=new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric"});

function kind(v:string){const x=v.toLowerCase();if(x.includes("bond"))return"Облигация";if(x.includes("share")||x.includes("stock"))return"Акция";if(x.includes("etf")||x.includes("fund"))return"Фонд";return v||"Актив"}
function isBond(v:string){return v.toLowerCase().includes("bond")}
function quote(position:PositionSnapshot,value:number){return priceFmt.format(value)+(isBond(position.instrumentType)?"%":" ₽")}
function matchSeries(position:PositionSnapshot,rows:AssetHistorySeries[]){
  const ids=[position.instrumentUid,position.figi].filter((x):x is string=>Boolean(x?.trim()));
  if(!ids.length)return null;
  const matches=rows.filter(row=>row.instrumentId!=null&&ids.includes(row.instrumentId));
  if(matches.length!==1)return null;
  const row=matches[0];
  return row.integrity==="VALID"&&row.points.length>=2?row:null;
}

export function V3AssetWorkspace({position,portfolioValue,shell,mode,onBack}:{position:PositionSnapshot;portfolioValue:number;shell:V3Shell;mode:V3DetailMode;onBack:()=>void}){
  const[view,setView]=useState<View>("overview"),[historyWindow,setHistoryWindow]=useState<V3HistoryWindow>("all"),[history,setHistory]=useState<AssetHistorySeries|null>(null),[historyState,setHistoryState]=useState<"loading"|"live"|"unavailable">("loading");
  useEffect(()=>{const controller=new AbortController();let active=true;setHistory(null);setHistoryState("loading");void loadAssetHistory(controller.signal,position.instrumentUid??position.figi??undefined).then(payload=>{if(!active)return;const matched=payload.available?matchSeries(position,payload.series):null;setHistory(matched);setHistoryState(matched?"live":"unavailable")}).catch(()=>{if(active)setHistoryState("unavailable")});return()=>{active=false;controller.abort()}},[position]);
  const visibleHistory=useMemo(()=>filterAssetHistoryWindow(history?.points??[],historyWindow),[history,historyWindow]),historySummary=summarizeAssetHistory(visibleHistory),basis=position.currentValue-position.expectedYield,pnlPct=basis>0?position.expectedYield/basis*100:null,weight=portfolioValue>0?position.currentValue/portfolioValue*100:position.weight;
  const chart=useMemo(()=>{if(visibleHistory.length<2)return null;const min=Math.min(...visibleHistory.map(x=>x.value)),max=Math.max(...visibleHistory.map(x=>x.value)),span=max-min||1,coords=visibleHistory.map((p,i)=>({x:i/(visibleHistory.length-1)*100,y:45-(p.value-min)/span*37})),line=coords.map(p=>`${p.x},${p.y}`).join(" "),area=`0,47 ${line} 100,47`;return{line,area,last:coords.at(-1)!}},[visibleHistory]);
  return <main className="v3-asset-workspace" data-shell={shell} data-mode={mode}>
    <button className="v3-asset-back" type="button" onClick={onBack}>← Активы</button>
    <header className="v3-asset-hero"><div><span>{kind(position.instrumentType)} · {position.ticker}</span><h1>{position.name}</h1><small>Текущая позиция из подтверждённого снимка портфеля</small></div><div className="v3-asset-hero-value"><strong>{quote(position,position.currentPrice)}</strong><span>{rub.format(position.currentValue)} ₽ · {plainPct.format(weight)}%</span><b className={position.expectedYield<0?"is-negative":""}>{position.expectedYield>=0?"+":""}{rub.format(position.expectedYield)} ₽ P/L</b></div></header>
    <nav className="v3-asset-workspace-tabs" aria-label="Раздел актива">{([["overview","Обзор"],["history","История"],["position","Позиция"]] as const).map(([id,label])=><button key={id} type="button" className={view===id?"is-active":""} aria-current={view===id?"page":undefined} onClick={()=>setView(id)}>{label}</button>)}</nav>
    {view==="overview"&&<><section className="v3-asset-workspace-grid"><article><span>Стоимость</span><strong>{rub.format(position.currentValue)} ₽</strong><small>текущий снимок</small></article><article><span>Доля</span><strong>{plainPct.format(weight)}%</strong><small>от капитала</small></article><article><span>Текущий P/L</span><strong className={position.expectedYield<0?"is-negative":""}>{position.expectedYield>=0?"+":""}{rub.format(position.expectedYield)} ₽</strong><small>{pnlPct==null?"процент недоступен":pct.format(pnlPct)+"% к базе"}</small></article><article><span>Количество</span><strong>{priceFmt.format(position.quantity)}</strong><small>единиц позиции</small></article></section><section className="v3-asset-method">P/L — накопленный результат позиции из брокерского снимка, не дневное изменение и не торговый сигнал.</section></>}
    {view==="history"&&<section className="v3-asset-history-card"><div className="v3-asset-history-head"><div><span>Официальная история цены</span><h2>{position.ticker}</h2></div><strong>{historyState==="loading"?"Загрузка":historyState==="live"?history!.points.length+" точек":"Нет покрытия"}</strong></div>{historyState==="loading"?<div className="v3-asset-history-empty">Получаем подтверждённые свечи инструмента…</div>:historyState==="unavailable"?<div className="v3-asset-history-empty">История недоступна или точная идентичность инструмента не подтверждена.</div>:<><V3HistoryWindowControl value={historyWindow} onChange={setHistoryWindow} label={"Период истории "+position.ticker}/>{chart&&<svg className="v3-asset-history-chart" viewBox="0 0 100 48" preserveAspectRatio="none" role="img" aria-label={"История цены "+position.ticker}><line x1="0" y1="25" x2="100" y2="25"/><polygon points={chart.area}/><polyline points={chart.line}/><circle cx={chart.last.x} cy={chart.last.y} r="1.5"/></svg>}{historySummary&&<><div className="v3-asset-history-caption"><span>{dateFmt.format(new Date(historySummary.startDate+"T00:00:00Z"))} · {quote(position,historySummary.first)}</span><strong className={historySummary.change!=null&&historySummary.change<0?"is-negative":""}>{historySummary.change==null?"—":pct.format(historySummary.change)+"%"}</strong><span>{dateFmt.format(new Date(historySummary.endDate+"T00:00:00Z"))} · {quote(position,historySummary.last)}</span></div><div className="v3-asset-history-stats"><article><span>Мин.</span><strong>{quote(position,historySummary.min)}</strong></article><article><span>Макс.</span><strong>{quote(position,historySummary.max)}</strong></article><article><span>Точек</span><strong>{historySummary.points}</strong></article></div></>}</>}<small className="v3-asset-source">Источник: T‑Invest GetCandles · пропуски не интерполируются · наблюдаемый период, не прогноз.</small></section>}
    {view==="position"&&<section className="v3-asset-workspace-grid is-position"><article><span>Количество</span><strong>{priceFmt.format(position.quantity)}</strong></article><article><span>Средняя цена</span><strong>{position.averagePrice>0?quote(position,position.averagePrice):"—"}</strong></article><article><span>Стоимость приобретения</span><strong>{position.costBasis>0?rub.format(position.costBasis)+" ₽":"—"}</strong></article><article><span>Текущая цена</span><strong>{position.currentPrice>0?quote(position,position.currentPrice):"—"}</strong></article><article><span>Текущая стоимость</span><strong>{rub.format(position.currentValue)} ₽</strong></article><article><span>Доля портфеля</span><strong>{plainPct.format(weight)}%</strong></article></section>}
  </main>
}
