import type{PayoutEvent,PayoutObservation}from"../../../v2/src/lib/payoutsApi";
const finite=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0;
const key=(value:string|null|undefined)=>{const raw=String(value||"").slice(0,7);return /^\d{4}-\d{2}$/.test(raw)?raw:null};
const monthRange=(from:string|null|undefined,to:string|null|undefined)=>{const a=key(from),b=key(to);if(!a||!b)return[] as string[];const [y,m]=a.split("-").map(Number),out:string[]=[];for(let i=0;i<36;i++){const d=new Date(Date.UTC(y!,m!-1+i,1)),k=d.toISOString().slice(0,7);if(k>b)break;out.push(k)}return out};
const net=(e:PayoutEvent)=>finite(e.net),gross=(e:PayoutEvent)=>finite(e.gross),tax=(e:PayoutEvent)=>finite(e.tax);
export type ActualIncomeMonth={key:string;net:number;gross:number;tax:number;count:number;couponNet:number;dividendNet:number;observation:"complete"|"partial"|"unknown"};
export type ActualIncomeSource={figi:string;label:string;net:number;count:number;share:number};
export type ActualIncomeHistory={available:boolean;from:string|null;to:string|null;months:ActualIncomeMonth[];totalNet:number;totalGross:number;totalTax:number;count:number;completeMonths:number;partialMonths:number;activeMonths:number;zeroCompleteMonths:number;averageCompleteMonthNet:number|null;medianActiveMonthNet:number|null;couponNet:number;dividendNet:number;couponShare:number|null;dividendShare:number|null;identifiedNet:number;unidentifiedNet:number;identityShare:number|null;sources:ActualIncomeSource[];latest:PayoutEvent[]};
export function buildActualIncomeHistory(items:PayoutEvent[],observation:PayoutObservation|undefined):ActualIncomeHistory{
 const obs=observation?.available?observation:undefined,monthsKeys=obs?monthRange(obs.from,obs.to):[...new Set(items.map(e=>key(e.date)).filter((x):x is string=>x!=null))].sort();
 const complete=new Set(obs?.completeMonths??[]),partial=new Set(obs?.partialMonths??[]),byMonth=new Map<string,PayoutEvent[]>();
 for(const event of items){const k=key(event.date);if(!k)continue;const row=byMonth.get(k)??[];row.push(event);byMonth.set(k,row)}
 const months=monthsKeys.map(k=>{const rows=byMonth.get(k)??[],couponNet=rows.filter(e=>String(e.kind).toUpperCase()==="COUPON").reduce((s,e)=>s+net(e),0),dividendNet=rows.filter(e=>String(e.kind).toUpperCase()==="DIVIDEND").reduce((s,e)=>s+net(e),0);return{key:k,net:rows.reduce((s,e)=>s+net(e),0),gross:rows.reduce((s,e)=>s+gross(e),0),tax:rows.reduce((s,e)=>s+tax(e),0),count:rows.length,couponNet,dividendNet,observation:complete.has(k)?"complete":partial.has(k)?"partial":"unknown" as const}});
 const totalNet=items.reduce((s,e)=>s+net(e),0),totalGross=items.reduce((s,e)=>s+gross(e),0),totalTax=items.reduce((s,e)=>s+tax(e),0),couponNet=items.filter(e=>String(e.kind).toUpperCase()==="COUPON").reduce((s,e)=>s+net(e),0),dividendNet=items.filter(e=>String(e.kind).toUpperCase()==="DIVIDEND").reduce((s,e)=>s+net(e),0),typed=couponNet+dividendNet;
 const completeValues=months.filter(m=>m.observation==="complete").map(m=>m.net),active=months.filter(m=>m.count>0),activeValues=active.map(m=>m.net).sort((a,b)=>a-b),medianActiveMonthNet=activeValues.length?activeValues[Math.floor((activeValues.length-1)/2)]!:null;
 const byFigi=new Map<string,{label:string;net:number;count:number}>();let identifiedNet=0;
 for(const e of items){const figi=String(e.figi||"").trim();if(!figi)continue;const n=net(e),current=byFigi.get(figi);identifiedNet+=n;if(current){current.net+=n;current.count++}else byFigi.set(figi,{label:e.ticker||e.name||figi,net:n,count:1})}
 const sources=[...byFigi.entries()].map(([figi,row])=>({figi,...row,share:identifiedNet>0?row.net/identifiedNet*100:0})).sort((a,b)=>b.net-a.net||a.label.localeCompare(b.label));
 return{available:Boolean(items.length||obs),from:obs?.from??null,to:obs?.to??null,months,totalNet,totalGross,totalTax,count:items.length,completeMonths:complete.size,partialMonths:partial.size,activeMonths:active.length,zeroCompleteMonths:months.filter(m=>m.observation==="complete"&&m.count===0).length,averageCompleteMonthNet:completeValues.length?completeValues.reduce((s,x)=>s+x,0)/completeValues.length:null,medianActiveMonthNet,couponNet,dividendNet,couponShare:typed>0?couponNet/typed*100:null,dividendShare:typed>0?dividendNet/typed*100:null,identifiedNet,unidentifiedNet:Math.max(0,totalNet-identifiedNet),identityShare:totalNet>0?identifiedNet/totalNet*100:null,sources,latest:[...items].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8)};
}
