import type{PayoutCalendar,PayoutEvent}from"../../../v2/src/lib/payoutsApi";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";
const finite=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:0,clean=(v:unknown)=>String(v??"").trim(),high=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH",near=(a:number,b:number)=>Math.abs(a-b)<0.01;
export type IncomeDataAuditIssue={code:string;label:string;detail:string};
export type IncomeDataAuditV85={available:boolean;stale:boolean;integrityComplete:boolean;scheduleCoverage:number;minimumCoverage:number;eligibleAssets:number;resolvedAssets:number;coverageErrors:number;actualCount:number;actualDeclaredNet:number;actualObservedNet:number;actualDelta:number;actualReconciles:boolean;actualFigiCount:number;actualFigiShare:number|null;actualFigiNet:number;actualFigiNetShare:number|null;observationAvailable:boolean;completeMonths:number;partialMonths:number;observationShare:number|null;highCount:number;highGross:number;forecastDeclaredGross:number;forecastDelta:number;forecastReconciles:boolean;highFigiCount:number;highFigiShare:number|null;highExactCount:number;highExactShare:number|null;highExactGross:number;highExactGrossShare:number|null;generatedAt:string|null;ageMinutes:number|null;issues:IncomeDataAuditIssue[]};
export function buildIncomeDataAuditV85(calendar:PayoutCalendar|null|undefined,positions:PositionSnapshot[],loadedAt:number=Date.now()):IncomeDataAuditV85{
 if(!calendar)return{available:false,stale:false,integrityComplete:false,scheduleCoverage:0,minimumCoverage:0,eligibleAssets:0,resolvedAssets:0,coverageErrors:0,actualCount:0,actualDeclaredNet:0,actualObservedNet:0,actualDelta:0,actualReconciles:false,actualFigiCount:0,actualFigiShare:null,actualFigiNet:0,actualFigiNetShare:null,observationAvailable:false,completeMonths:0,partialMonths:0,observationShare:null,highCount:0,highGross:0,forecastDeclaredGross:0,forecastDelta:0,forecastReconciles:false,highFigiCount:0,highFigiShare:null,highExactCount:0,highExactShare:null,highExactGross:0,highExactGrossShare:null,generatedAt:null,ageMinutes:null,issues:[{code:"NO_CALENDAR",label:"Календарь недоступен",detail:"Проверка целостности не выполняется без источника."}]};
 const actual=calendar.actual.items??[],actualObservedNet=actual.reduce((s,e)=>s+finite(e.net),0),actualDeclaredNet=finite(calendar.actual.totalNet),actualDelta=actualDeclaredNet-actualObservedNet,actualFigi=actual.filter(e=>clean(e.figi)),actualFigiNet=actualFigi.reduce((s,e)=>s+finite(e.net),0);
 const future=(calendar.events??[]).filter(high),highGross=future.reduce((s,e)=>s+Math.max(0,finite(e.gross)),0),forecastDeclaredGross=finite(calendar.forecast.gross),forecastDelta=forecastDeclaredGross-highGross,highFigi=future.filter(e=>clean(e.figi));
 const groups=new Map<string,PositionSnapshot[]>();for(const p of positions){const f=clean(p.figi);if(!f)continue;const rows=groups.get(f)??[];rows.push(p);groups.set(f,rows)}const exact=future.filter(e=>{const f=clean(e.figi);return f&&groups.get(f)?.length===1}),highExactGross=exact.reduce((s,e)=>s+Math.max(0,finite(e.gross)),0);
 const obs=calendar.actual.observation,complete=obs?.available?obs.completeMonths.length:0,partial=obs?.available?obs.partialMonths.length:0,totalObs=complete+partial,generatedAt=calendar.generatedAt??null,generatedMs=generatedAt?Date.parse(generatedAt):NaN,ageMinutes=Number.isFinite(generatedMs)?Math.max(0,(loadedAt-generatedMs)/60000):null;
 const issues:IncomeDataAuditIssue[]=[];if(calendar.stale)issues.push({code:"STALE",label:"Источник устарел",detail:"Календарь помечен источником как stale."});if(!calendar.integrity.complete)issues.push({code:"INTEGRITY",label:"Неполная целостность",detail:"Источник не подтвердил полный набор проверок расписания."});if(calendar.coverage.coverageRatio<calendar.integrity.minimumCoverage)issues.push({code:"COVERAGE",label:"Покрытие ниже порога",detail:`${Math.round(calendar.coverage.coverageRatio*100)}% при минимуме ${Math.round(calendar.integrity.minimumCoverage*100)}%.`});if(calendar.coverage.errors.length)issues.push({code:"COVERAGE_ERRORS",label:"Есть ошибки покрытия",detail:`Ошибок источника: ${calendar.coverage.errors.length}.`});if(!near(actualDeclaredNet,actualObservedNet))issues.push({code:"ACTUAL_RECONCILE",label:"FACT net не сходится",detail:`Расхождение агрегата и событий: ${actualDelta.toFixed(2)} ₽.`});if(!near(forecastDeclaredGross,highGross))issues.push({code:"FUTURE_RECONCILE",label:"FUTURE gross не сходится",detail:`Расхождение агрегата и HIGH-событий: ${forecastDelta.toFixed(2)} ₽.`});if(future.length&&exact.length<future.length)issues.push({code:"IDENTITY",label:"Не все HIGH-события связаны",detail:`Точное совпадение FIGI: ${exact.length}/${future.length} событий.`});
 return{available:calendar.available,stale:calendar.stale,integrityComplete:calendar.integrity.complete,scheduleCoverage:calendar.coverage.coverageRatio,minimumCoverage:calendar.integrity.minimumCoverage,eligibleAssets:calendar.coverage.eligibleAssets,resolvedAssets:calendar.coverage.resolvedAssets,coverageErrors:calendar.coverage.errors.length,actualCount:actual.length,actualDeclaredNet,actualObservedNet,actualDelta,actualReconciles:near(actualDeclaredNet,actualObservedNet),actualFigiCount:actualFigi.length,actualFigiShare:actual.length?actualFigi.length/actual.length*100:null,actualFigiNet,actualFigiNetShare:actualObservedNet?actualFigiNet/actualObservedNet*100:null,observationAvailable:obs?.available===true,completeMonths:complete,partialMonths:partial,observationShare:totalObs?complete/totalObs*100:null,highCount:future.length,highGross,forecastDeclaredGross,forecastDelta,forecastReconciles:near(forecastDeclaredGross,highGross),highFigiCount:highFigi.length,highFigiShare:future.length?highFigi.length/future.length*100:null,highExactCount:exact.length,highExactShare:future.length?exact.length/future.length*100:null,highExactGross,highExactGrossShare:highGross?highExactGross/highGross*100:null,generatedAt,ageMinutes,issues};
}
