import type{PayoutEvent}from"../../../v2/src/lib/payoutsApi";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";
const msDay=86_400_000,clean=(x:unknown)=>String(x??"").trim(),day=(x:unknown)=>{const s=String(x??"").slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+"T00:00:00Z"))?s:null},finite=(x:unknown)=>typeof x==="number"&&Number.isFinite(x)?x:0,isHigh=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH";
export type IncomeTimelineKind="ALL"|"COUPON"|"DIVIDEND";
export type IncomeTimelineRow={side:"FACT"|"FUTURE";date:string;daysFromAnchor:number;kind:string;label:string;figi:string|null;amount:number;amountBasis:"NET"|"GROSS";position:PositionSnapshot|null};
export type IncomeTimeline={available:boolean;anchorDate:string|null;past:IncomeTimelineRow[];future:IncomeTimelineRow[];pastCount:number;futureCount:number;nearestPastDays:number|null;nearestFutureDays:number|null};
export function buildIncomeTimeline(actual:PayoutEvent[],future:PayoutEvent[],positions:PositionSnapshot[],anchorValue:string|null|undefined,kind:IncomeTimelineKind="ALL"):IncomeTimeline{
 const anchor=day(anchorValue);if(!anchor)return{available:false,anchorDate:null,past:[],future:[],pastCount:0,futureCount:0,nearestPastDays:null,nearestFutureDays:null};
 const anchorMs=Date.parse(anchor+"T00:00:00Z"),match=(e:PayoutEvent)=>{const f=clean(e.figi);if(!f)return null;const m=positions.filter(p=>clean(p.figi)===f);return m.length===1?m[0]!:null},accept=(e:PayoutEvent)=>kind==="ALL"||String(e.kind).toUpperCase()===kind;
 const past=actual.filter(accept).map(e=>{const d=day(e.date);if(!d)return null;const delta=Math.floor((Date.parse(d+"T00:00:00Z")-anchorMs)/msDay);return delta>0?null:{side:"FACT" as const,date:d,daysFromAnchor:delta,kind:String(e.kind).toUpperCase(),label:e.ticker||e.name||"—",figi:clean(e.figi)||null,amount:finite(e.net),amountBasis:"NET" as const,position:match(e)}}).filter((x):x is NonNullable<typeof x>=>x!=null).sort((a,b)=>b.date.localeCompare(a.date));
 const futureRows=future.filter(e=>isHigh(e)&&accept(e)).map(e=>{const d=day(e.date);if(!d)return null;const delta=Math.floor((Date.parse(d+"T00:00:00Z")-anchorMs)/msDay);return delta<0?null:{side:"FUTURE" as const,date:d,daysFromAnchor:delta,kind:String(e.kind).toUpperCase(),label:e.ticker||e.name||"—",figi:clean(e.figi)||null,amount:Math.max(0,finite(e.gross)),amountBasis:"GROSS" as const,position:match(e)}}).filter((x):x is NonNullable<typeof x>=>x!=null).sort((a,b)=>a.date.localeCompare(b.date));
 return{available:true,anchorDate:anchor,past,future:futureRows,pastCount:past.length,futureCount:futureRows.length,nearestPastDays:past[0]?Math.abs(past[0].daysFromAnchor):null,nearestFutureDays:futureRows[0]?.daysFromAnchor??null};
}