import type{PayoutEvent}from"../../../v2/src/lib/payoutsApi";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";
const msDay=86_400_000,clean=(x:unknown)=>String(x??"").trim(),day=(x:unknown)=>{const s=String(x??"").slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+"T00:00:00Z"))?s:null},gross=(e:PayoutEvent)=>typeof e.gross==="number"&&Number.isFinite(e.gross)?Math.max(0,e.gross):0,isHigh=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH";
export type IncomeExplorerKind="ALL"|"COUPON"|"DIVIDEND";export type IncomeExplorerLink="ALL"|"LINKED"|"UNLINKED";export type IncomeExplorerSort="DATE"|"AMOUNT";
export type IncomeExplorerRow={event:PayoutEvent;date:string;days:number;gross:number;position:PositionSnapshot|null;linked:boolean};
export type IncomeExplorer={available:boolean;rows:IncomeExplorerRow[];gross:number;count:number;linkedCount:number;unlinkedCount:number;horizon:number;kind:IncomeExplorerKind;link:IncomeExplorerLink;sort:IncomeExplorerSort};
export function buildIncomeEventExplorer(events:PayoutEvent[],positions:PositionSnapshot[],anchorValue:string|null|undefined,{horizon=365,kind="ALL",link="ALL",sort="DATE"}:{horizon?:number;kind?:IncomeExplorerKind;link?:IncomeExplorerLink;sort?:IncomeExplorerSort}={}):IncomeExplorer{
 const anchor=day(anchorValue);if(!anchor)return{available:false,rows:[],gross:0,count:0,linkedCount:0,unlinkedCount:0,horizon,kind,link,sort};const anchorMs=Date.parse(anchor+"T00:00:00Z");
 const rows=events.filter(isHigh).map(event=>{const d=day(event.date);if(!d)return null;const days=Math.floor((Date.parse(d+"T00:00:00Z")-anchorMs)/msDay);if(days<0||days>horizon)return null;if(kind!=="ALL"&&String(event.kind).toUpperCase()!==kind)return null;const f=clean(event.figi),m=f?positions.filter(p=>clean(p.figi)===f):[],position=m.length===1?m[0]!:null,linked=Boolean(position);if(link==="LINKED"&&!linked||link==="UNLINKED"&&linked)return null;return{event,date:d,days,gross:gross(event),position,linked}}).filter((x):x is NonNullable<typeof x>=>x!=null);
 rows.sort(sort==="AMOUNT"?(a,b)=>b.gross-a.gross||a.date.localeCompare(b.date):(a,b)=>a.date.localeCompare(b.date)||b.gross-a.gross);
 return{available:true,rows,gross:rows.reduce((s,r)=>s+r.gross,0),count:rows.length,linkedCount:rows.filter(r=>r.linked).length,unlinkedCount:rows.filter(r=>!r.linked).length,horizon,kind,link,sort};
}