import type{PayoutEvent}from"../../../v2/src/lib/payoutsApi";
const clean=(x:unknown)=>String(x??"").trim(),gross=(e:PayoutEvent)=>typeof e.gross==="number"&&Number.isFinite(e.gross)&&e.gross>0?e.gross:0,isHigh=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH",month=(x:unknown)=>{const k=String(x??"").slice(0,7);return /^\d{4}-\d{2}$/.test(k)?k:null};
export type MonthSourceRow={figi:string;label:string;gross:number;count:number;share:number;couponGross:number;dividendGross:number;amountKnown:number};
export type MonthSourceComposition={available:boolean;month:string|null;gross:number;count:number;amountCoverageRatio:number|null;identifiedGross:number;identifiedCount:number;unidentifiedGross:number;unidentifiedCount:number;identityGrossShare:number|null;sources:MonthSourceRow[];sourceCount:number;top1Share:number|null;top3Share:number|null;hhi:number|null;effectiveSources:number|null;couponGross:number;dividendGross:number;couponShare:number|null;dividendShare:number|null};
export function buildIncomeMonthSourceComposition(events:PayoutEvent[],monthKey:string|null|undefined):MonthSourceComposition{
 const target=month(monthKey);if(!target)return{available:false,month:null,gross:0,count:0,amountCoverageRatio:null,identifiedGross:0,identifiedCount:0,unidentifiedGross:0,unidentifiedCount:0,identityGrossShare:null,sources:[],sourceCount:0,top1Share:null,top3Share:null,hhi:null,effectiveSources:null,couponGross:0,dividendGross:0,couponShare:null,dividendShare:null};
 const selected=events.filter(e=>isHigh(e)&&month(e.date)===target),byFigi=new Map<string,{label:string;gross:number;count:number;couponGross:number;dividendGross:number;amountKnown:number}>();let totalGross=0,known=0,identifiedGross=0,identifiedCount=0,unidentifiedGross=0,unidentifiedCount=0,couponGross=0,dividendGross=0;
 for(const e of selected){const g=gross(e),figi=clean(e.figi),kind=String(e.kind||"").toUpperCase();totalGross+=g;if(g>0)known++;if(kind==="COUPON")couponGross+=g;else if(kind==="DIVIDEND")dividendGross+=g;if(!figi){unidentifiedGross+=g;unidentifiedCount++;continue}identifiedGross+=g;identifiedCount++;const row=byFigi.get(figi)??{label:e.ticker||e.name||figi,gross:0,count:0,couponGross:0,dividendGross:0,amountKnown:0};row.gross+=g;row.count++;if(g>0)row.amountKnown++;if(kind==="COUPON")row.couponGross+=g;else if(kind==="DIVIDEND")row.dividendGross+=g;byFigi.set(figi,row)}
 const sources=[...byFigi.entries()].map(([figi,row])=>({figi,...row,share:identifiedGross>0?row.gross/identifiedGross:0})).sort((a,b)=>b.gross-a.gross||a.label.localeCompare(b.label)),shares=sources.filter(r=>r.gross>0).map(r=>r.share),sq=shares.reduce((s,x)=>s+x*x,0),typed=couponGross+dividendGross,top1=sources[0]?.share??null,top3=sources.slice(0,3).reduce((s,r)=>s+r.share,0);
 return{available:true,month:target,gross:totalGross,count:selected.length,amountCoverageRatio:selected.length?known/selected.length:null,identifiedGross,identifiedCount,unidentifiedGross,unidentifiedCount,identityGrossShare:totalGross>0?identifiedGross/totalGross:null,sources,sourceCount:sources.length,top1Share:top1,top3Share:sources.length?top3:null,hhi:sq>0?sq*10_000:null,effectiveSources:sq>0?1/sq:null,couponGross,dividendGross,couponShare:typed>0?couponGross/typed:null,dividendShare:typed>0?dividendGross/typed:null};
}
