import type{PayoutEvent}from"../../../v2/src/lib/payoutsApi";import type{IncomeForwardMonths}from"./incomeForwardWindow";
const gross=(e:PayoutEvent)=>typeof e.gross==="number"&&Number.isFinite(e.gross)&&e.gross>0?e.gross:0,isHigh=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH";
const monthKey=(value:unknown)=>{const key=String(value??"").slice(0,7);return /^\d{4}-\d{2}$/.test(key)&&Number(key.slice(5,7))>=1&&Number(key.slice(5,7))<=12?key:null};
const monthRange=(anchorMs:number,months:IncomeForwardMonths)=>{const d=new Date(anchorMs),y=d.getUTCFullYear(),m=d.getUTCMonth();return Array.from({length:months},(_,i)=>new Date(Date.UTC(y,m+i,1)).toISOString().slice(0,7))};
export type ForwardCadenceMonth={key:string;gross:number;count:number;coupons:number;dividends:number;couponGross:number;dividendGross:number;amountKnown:number;events:PayoutEvent[]};
export type ForwardCadence={available:boolean;months:ForwardCadenceMonth[];totalGross:number;count:number;amountCoverageRatio:number|null;activeMonths:number;zeroMonths:number;longestGap:number;peakMonth:ForwardCadenceMonth|null;first90Gross:number;first90Share:number|null;couponGross:number;dividendGross:number;couponShare:number|null;dividendShare:number|null;monthlyHhi:number|null;effectiveMonths:number|null};
export function buildIncomeForwardCadence(events:PayoutEvent[],anchorMs:number,window:IncomeForwardMonths):ForwardCadence{
 if(!Number.isFinite(anchorMs))return{available:false,months:[],totalGross:0,count:0,amountCoverageRatio:null,activeMonths:0,zeroMonths:0,longestGap:0,peakMonth:null,first90Gross:0,first90Share:null,couponGross:0,dividendGross:0,couponShare:null,dividendShare:null,monthlyHhi:null,effectiveMonths:null};
 const keys=monthRange(anchorMs,window),keySet=new Set(keys),rows=new Map(keys.map(key=>[key,{key,gross:0,count:0,coupons:0,dividends:0,couponGross:0,dividendGross:0,amountKnown:0,events:[]} as ForwardCadenceMonth]));let totalGross=0,count=0,known=0,first90Gross=0,couponGross=0,dividendGross=0;
 const cutoff=anchorMs+90*86_400_000;
 for(const event of events.filter(isHigh)){const t=Date.parse(event.date);if(!Number.isFinite(t)||t<anchorMs)continue;const key=monthKey(event.date);if(!key||!keySet.has(key))continue;const row=rows.get(key)!,g=gross(event),k=String(event.kind||"").toUpperCase();row.events.push(event);row.count++;count++;row.gross+=g;totalGross+=g;if(g>0){row.amountKnown++;known++}if(t<=cutoff)first90Gross+=g;if(k==="COUPON"){row.coupons++;row.couponGross+=g;couponGross+=g}else if(k==="DIVIDEND"){row.dividends++;row.dividendGross+=g;dividendGross+=g}}
 const months=[...rows.values()],activeMonths=months.filter(x=>x.count>0).length,zeroMonths=months.length-activeMonths;let gap=0,longestGap=0;for(const row of months){if(row.count===0){gap++;longestGap=Math.max(longestGap,gap)}else gap=0}const peakMonth=months.reduce<ForwardCadenceMonth|null>((best,row)=>row.gross>(best?.gross??-1)&&row.count>0?row:best,null);const shares=totalGross>0?months.filter(x=>x.gross>0).map(x=>x.gross/totalGross):[],monthlyHhi=shares.length?shares.reduce((s,x)=>s+x*x,0)*10_000:null,effectiveMonths=shares.length?1/shares.reduce((s,x)=>s+x*x,0):null,typedGross=couponGross+dividendGross;
 return{available:true,months,totalGross,count,amountCoverageRatio:count?known/count:null,activeMonths,zeroMonths,longestGap,peakMonth,first90Gross,first90Share:totalGross>0?first90Gross/totalGross:null,couponGross,dividendGross,couponShare:typedGross>0?couponGross/typedGross:null,dividendShare:typedGross>0?dividendGross/typedGross:null,monthlyHhi,effectiveMonths};
}
