import type{PayoutEvent}from"../../../v2/src/lib/payoutsApi";import type{PositionSnapshot}from"../../../v2/src/lib/portfolioApi";
const clean=(x:unknown)=>String(x??"").trim(),month=(x:unknown)=>{const s=String(x??"").slice(0,7);return /^\d{4}-\d{2}$/.test(s)&&Number(s.slice(5,7))>=1&&Number(s.slice(5,7))<=12?s:null},gross=(e:PayoutEvent)=>typeof e.gross==="number"&&Number.isFinite(e.gross)?Math.max(0,e.gross):0,isHigh=(e:PayoutEvent)=>String(e.status||"").toUpperCase()!=="FACT"&&String(e.confidence||"").toUpperCase()==="HIGH";
const range=(from:string|null|undefined,to:string|null|undefined)=>{const a=month(from),b=month(to);if(!a||!b)return[] as string[];const[y,m]=a.split("-").map(Number),out:string[]=[];for(let i=0;i<24;i++){const d=new Date(Date.UTC(y!,m!-1+i,1)),k=d.toISOString().slice(0,7);if(k>b)break;out.push(k)}return out};
export type IncomeMatrixCell={month:string;gross:number;count:number;couponGross:number;dividendGross:number};
export type IncomeMatrixRow={position:PositionSnapshot;gross:number;count:number;activeMonths:number;cells:IncomeMatrixCell[]};
export type IncomeSourceMonthMatrix={available:boolean;months:string[];rows:IncomeMatrixRow[];monthly:IncomeMatrixCell[];matchedGross:number;matchedCount:number;unmatchedGross:number;unmatchedCount:number;activeSources:number;activeCells:number;totalCells:number;density:number|null;peakCell:{ticker:string;month:string;gross:number}|null};
export function buildIncomeSourceMonthMatrix(events:PayoutEvent[],positions:PositionSnapshot[],fromValue:string|null|undefined,toValue:string|null|undefined):IncomeSourceMonthMatrix{
 const months=range(fromValue,toValue);if(!months.length)return{available:false,months:[],rows:[],monthly:[],matchedGross:0,matchedCount:0,unmatchedGross:0,unmatchedCount:0,activeSources:0,activeCells:0,totalCells:0,density:null,peakCell:null};const keys=new Set(months),positionGroups=new Map<string,PositionSnapshot[]>(),byFigi=new Map<string,IncomeMatrixRow>();for(const p of positions){const f=clean(p.figi);if(!f)continue;const rows=positionGroups.get(f)??[];rows.push(p);positionGroups.set(f,rows)}for(const[f,rows]of positionGroups)if(rows.length===1)byFigi.set(f,{position:rows[0]!,gross:0,count:0,activeMonths:0,cells:months.map(k=>({month:k,gross:0,count:0,couponGross:0,dividendGross:0}))});
 let matchedGross=0,matchedCount=0,unmatchedGross=0,unmatchedCount=0;const monthly=months.map(k=>({month:k,gross:0,count:0,couponGross:0,dividendGross:0}));
 for(const e of events.filter(isHigh)){const k=month(e.date);if(!k||!keys.has(k))continue;const g=gross(e),f=clean(e.figi),row=f?byFigi.get(f):undefined;if(!row){unmatchedGross+=g;unmatchedCount++;continue}const cell=row.cells[months.indexOf(k)]!,total=monthly[months.indexOf(k)]!;cell.gross+=g;cell.count++;total.gross+=g;total.count++;if(String(e.kind).toUpperCase()==="COUPON"){cell.couponGross+=g;total.couponGross+=g}else if(String(e.kind).toUpperCase()==="DIVIDEND"){cell.dividendGross+=g;total.dividendGross+=g}row.gross+=g;row.count++;matchedGross+=g;matchedCount++}
 const rows=[...byFigi.values()].filter(r=>r.count>0).map(r=>({...r,activeMonths:r.cells.filter(c=>c.count>0).length})).sort((a,b)=>b.gross-a.gross||a.position.ticker.localeCompare(b.position.ticker));const activeCells=rows.reduce((s,r)=>s+r.activeMonths,0),totalCells=rows.length*months.length;let peakCell:IncomeSourceMonthMatrix["peakCell"]=null;for(const r of rows)for(const c of r.cells)if(c.gross>0&&(!peakCell||c.gross>peakCell.gross))peakCell={ticker:r.position.ticker,month:c.month,gross:c.gross};return{available:true,months,rows,monthly,matchedGross,matchedCount,unmatchedGross,unmatchedCount,activeSources:rows.length,activeCells,totalCells,density:totalCells?activeCells/totalCells*100:null,peakCell};
}
