import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
const app=readFileSync(new URL("../src/app/V3App.tsx",import.meta.url),"utf8");
const analysis=readFileSync(new URL("../src/analysis/V3Analysis.tsx",import.meta.url),"utf8");
const depth=readFileSync(new URL("../src/analysis/analysisDepth.ts",import.meta.url),"utf8");
assert.match(app,/loadV3Analysis=\(\)=>import\("\.\.\/analysis\/V3Analysis"\)/);
assert.match(app,/V3Analysis=lazy\(loadV3Analysis\)/);
assert.doesNotMatch(app,/import\{V3Analysis\}from/);
assert.match(app,/workspace==="analysis"\?<Suspense/);
assert.match(app,/V3WorkspaceLoading/);
assert.match(app,/void loadV3Analysis\(\);void loadV3AssetWorkspace\(\);void loadV3DnaWorkspace\(\)/);
assert.doesNotMatch(app,/setTimeout\(\(\)=>\{void loadV3Analysis/);
for(const fn of["calculatePortfolioAnalytics","calculateRelativePerformance","calculateRollingRisk","calculateTailRisk"])assert.match(depth,new RegExp(fn));
for(const layer of["V3ReturnLayer","V3RiskLayer","V3MarketLayer"])assert.match(analysis,new RegExp(layer));
assert.match(analysis,/useState<"overview"\|"return"\|"risk"\|"structure"\|"market">/);
console.log("v3 preloaded analytics engine contracts: ok");
