import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const chart=fs.readFileSync(new URL("../src/home/V3HistorySparkline.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
assert.match(chart,/export type V3HistoryChartMode="value"\|"performance"/);
assert.match(chart,/windowValue\?:V3HistoryWindow/);
assert.match(chart,/modeValue\?:V3HistoryChartMode/);
assert.match(chart,/onWindowChange\?\:\(value:V3HistoryWindow\)=>void/);
assert.match(chart,/onModeChange\?\:\(value:V3HistoryChartMode\)=>void/);
assert.match(core,/function ResultPeriodCockpit/);
assert.match(core,/filterHistoryWindow\(history,window\)/);
assert.match(core,/summarizeHistoryValue\(rows\)/);
assert.match(core,/ВЫБРАННЫЙ ПЕРИОД/);
assert.match(core,/Изменение стоимости включает пополнения и не является доходностью стратегии/);
assert.match(core,/Разница с IMOEX описывает только выбранный исторический период и не является прогнозом/);
assert.match(core,/windowValue=\{resultWindow\}/);
assert.match(core,/modeValue=\{resultChartMode\}/);
assert.match(css,/v64 · synchronized performance cockpit/);
assert.match(css,/\.sb-result-period\[data-mode="performance"\]/);
assert.doesNotMatch(core,/прогноз цены|рекомендую|купить|продать/iu);
console.log("corePerformanceCockpitV64: ok");