import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
const light=fs.readFileSync(new URL("../src/core/lightCoreProTools.css",import.meta.url),"utf8");
const tools=fs.readFileSync(new URL("../src/analysis/V3AnalysisToolbox.tsx",import.meta.url),"utf8");
assert.match(core,/data-kind=\{kind\}/);
assert.match(core,/К активам/);
assert.match(core,/Карта позиций/);
const guide=core.slice(core.indexOf("function WorkspaceGuide"),core.indexOf("function PortfolioContributionMap"));
assert.doesNotMatch(guide,/onHub\("market"\)|onHub\("tools"\)/,"analytics guide must not duplicate the primary hub tabs");
assert.match(tools,/useState\(false\)/,"tools catalog should start closed so the calculation is immediately visible");
assert.match(css,/v68 · mobile density \+ navigation simplification/);
assert.match(css,/grid-template-areas:"identity weight value pnl"/);
assert.match(css,/min-height:48px/);
assert.match(css,/\.sb-workspace-guide__routes\[data-kind="analytics"\]/);
assert.match(light,/v68 · direct-to-calculation professional mobile flow/);
assert.match(light,/\.sb \.v3-pro-tools>header p\{display:none\}/);
assert.match(light,/\.sb \.v3-market-intelligence>header p\{display:none\}/);
console.log("coreMobileDensityNavigationV68: ok");