import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
assert.match(core,/function WorkspaceGuide/,"workspace navigator must exist");
assert.match(core,/РАБОЧИЙ НАВИГАТОР/);
assert.match(core,/От общего состава к влиянию конкретной бумаги/);
assert.match(core,/От структуры портфеля к рынку и инструментам/);
assert.match(core,/openPortfolioWorkspace=\(mode:/);
assert.match(core,/openAnalyticsWorkspace=\(mode:AnalyticsMode="risk"\)/);
assert.match(core,/onPortfolioWorkspace=\{openPortfolioWorkspace\}/);
assert.match(core,/onAnalyticsWorkspace=\{openAnalyticsWorkspace\}/);
assert.match(core,/Сравнить<\/button>/);
assert.match(core,/Карта влияния/);
assert.match(core,/Риск портфеля/);
assert.match(core,/data-count=\{items\.length\}/);
assert.match(css,/v63 · Snowball\+ workspace flow/);
assert.match(css,/\.sb-workspace-guide__routes/);
assert.match(css,/\.sb-switch\[data-count="5"\]/);
assert.match(css,/\.sb-asset-commandbar\{display:flex/);
assert.doesNotMatch(core,/рекомендую|покупать|продавать/iu);
console.log("coreWorkspaceFlowV63: ok");