import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";const root=readFileSync(new URL("../src/core/CoreRoot.tsx",import.meta.url),"utf8"),pay=readFileSync(new URL("../src/core/CorePayoutCalendar.tsx",import.meta.url),"utf8");test("cold start retries automatically with bounded backoff",()=>{for(const x of["3000","7000","15000","30000","60000","scheduleRetry"])assert.ok(root.includes(x));assert.match(root,/cached\.current/)});test("successful trusted read cancels recovery loop",()=>{assert.match(root,/retryStep\.current=0/);assert.match(root,/clearTimeout\(retryTimer\.current\)/)});test("payout calendar also retries transient cold-start failure",()=>{assert.match(pay,/retryRef/);assert.match(pay,/\.catch/);assert.match(pay,/setAttempt/)});

test("trusted recovery continues while a cached snapshot is displayed",()=>{const start=root.indexOf("const scheduleRetry");const end=root.indexOf("const refresh=",start);const schedule=root.slice(start,end);assert.doesNotMatch(schedule,/cached\.current/);assert.match(root,/повторяем загрузку автоматически/);assert.match(root,/\[refreshing,setRefreshing\]=useState\(false\)/)});
const preview=readFileSync(new URL("../preview-server.cjs",import.meta.url),"utf8");
test("preview proxy retries transient Render wake failures for safe reads",()=>{assert.match(preview,/safeRetry=method==="GET"\|\|method==="HEAD"/);assert.match(preview,/retryable=new Set\(\[502,503,504\]\)/);assert.match(preview,/delays=isDashboard\?\[0,1200,2500,4500,7000,10000,14000,18000\]:isBrokerRecovery\?\[0,900,1800,3200,5200,8000,12000\]:\[0,1200,2600,5000\]/);assert.match(preview,/attemptTimeoutMs=isDashboard\?9000:isBrokerRecovery\?7000:18000/);assert.match(preview,/QVANIX_DASHBOARD_PROXY/);assert.match(preview,/QVANIX_BROKER_RECOVERY_PROXY/)});
test("preview startup probes only the lightweight version endpoint",()=>{const start=preview.indexOf("function probeUpstream");const end=preview.indexOf("const types=",start);const probe=preview.slice(start,end);assert.match(probe,/const route="\/api\/version"/);assert.doesNotMatch(probe,/\/api\/dashboard/);assert.doesNotMatch(probe,/\/api\/portfolio/)});

const payouts=readFileSync(new URL("../../v2/src/lib/payoutsApi.ts",import.meta.url),"utf8");
test("trusted Core prewarms slow read-only workspaces without blocking portfolio paint",()=>{assert.match(root,/loadMarketScreener\(\)/);assert.match(root,/loadPayoutCalendar\(\{timeoutMs:8000\}\)/);assert.match(root,/setTimeout\(\(\)=>\{/);assert.match(root,/Promise\.allSettled/)});
test("unavailable payout responses are not cached as if healthy",()=>{assert.match(payouts,/cacheEnabled&&result\.available/);assert.doesNotMatch(payouts,/if\(cacheEnabled\)payoutCache=\{value:result/)})

test("deep financial chunks prefetch only after trusted first paint",()=>{assert.match(root,/import\(\"\.\.\/assets\/V3AssetsDepth\"\)/);assert.match(root,/import\(\"\.\.\/analysis\/V3MarketIntelligenceWorkspace\"\)/);assert.match(root,/import\(\"\.\.\/analysis\/V3AnalysisToolbox\"\)/);assert.match(root,/1400/)});


test("verified legacy broker fallback stays visible while Core retries the full dashboard",()=>{assert.match(root,/nextSnapshot\.source==="portfolio"/);assert.match(root,/Основной dashboard временно недоступен/);assert.match(root,/retryStep\.current=Math\.max\(retryStep\.current,3\)/);assert.match(root,/scheduleRetry\(\)/)});