import fs from"node:fs";import assert from"node:assert/strict";
const calendar=fs.readFileSync(new URL("../src/core/CorePayoutCalendar.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/corePayoutCalendar.css",import.meta.url),"utf8");
assert.match(calendar,/buildPayoutRunway/);
assert.match(calendar,/12М РИТМ ПОТОКА/);
assert.match(calendar,/Подтверждённый календарный профиль/);
assert.match(calendar,/Активных месяцев/);
assert.match(calendar,/Пиковый месяц/);
assert.match(calendar,/Макс\. разрыв/);
assert.match(calendar,/Средний активный месяц/);
assert.match(calendar,/не прогноз/);
assert.match(calendar,/Купоны/);
assert.match(calendar,/Дивиденды/);
assert.match(calendar,/Пустой месяц означает отсутствие подтверждённого события/);
assert.match(calendar,/qpay-runway--compact/);
assert.match(css,/v73 · confirmed 12m payout runway/);
assert.match(css,/\.qpay-runway-bars/);
assert.match(css,/\.qpay-runway-split/);
console.log("coreIncomeRunwayV73: ok");