import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
assert.match(core,/sb-asset-commandbar/);
assert.match(core,/Навигация и действия по бумаге/);
assert.match(core,/sb-asset-commandbar__back/);
assert.match(core,/Сравнить/);
assert.match(core,/Карта/);
assert.match(core,/Риск/);
assert.match(core,/<details className="sb-detail-section sb-asset-math">/);
assert.match(core,/<summary>Как читается позиция<\/summary>/);
assert.doesNotMatch(core,/className="sb-asset-jump"/);
assert.doesNotMatch(core,/className="sb-asset-next"/);
assert.match(css,/v69 · asset command density/);
assert.match(css,/\.sb-asset-commandbar\{display:flex/);
assert.match(css,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/);
assert.match(css,/\.sb-asset-answer>small\{display:none\}/);
assert.match(css,/\.sb-asset-context__metrics\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/);
console.log("coreAssetCommandDensityV69: ok");