import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const fallen=fs.readFileSync(new URL("../src/analysis/V3FallenAssetsDiscovery.tsx",import.meta.url),"utf8");
const layer=fs.readFileSync(new URL("../src/analysis/V3MarketLayer.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
assert.match(core,/Концентрация топ-3[\s\S]*neutralPct\.format/,"top-3 concentration must use unsigned formatter");
assert.match(core,/ПОЗИЦИЯ В ПОРТФЕЛЕ[\s\S]*neutralPct\.format\(w\)/,"portfolio weight must not use signed formatter");
assert.match(core,/Включить профессиональный режим: открыть глубокую аналитику/);
assert.match(core,/Включить простой режим: скрыть глубокую аналитику/);
assert.doesNotMatch(fallen,/TECHNICAL DISCOVERY|Discovery v1|технический discovery|>落</u);
assert.match(fallen,/ТЕХНИЧЕСКАЯ ИСТОРИЯ/);
assert.match(fallen,/<svg viewBox="0 0 24 24"/);
assert.doesNotMatch(layer,/>Preview<|>Conflict<|>Gate<|>Excess<|Tracking Error|Information Ratio/);
assert.match(layer,/Предварительно/);
assert.match(layer,/Недостаточно данных/);
assert.match(layer,/Разница с IMOEX/);
assert.match(layer,/Ошибка слежения/);
assert.match(layer,/Информационное отношение/);
assert.match(css,/v61 · consistency polish from council audit/);
console.log("coreCouncilPolishV61: ok");