import fs from"node:fs";import assert from"node:assert/strict";
const core=fs.readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8");
const chart=fs.readFileSync(new URL("../src/assets/V3AssetHistoryChart.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/core/snowballCore.css",import.meta.url),"utf8");
assert.match(chart,/averageLine=position\.averagePrice>0/);
assert.match(chart,/brokerLine=position\.currentPrice>0/);
assert.match(chart,/v3-asset-history-entry/);
assert.match(chart,/v3-asset-history-broker/);
assert.match(chart,/Средняя позиции/);
assert.match(chart,/Текущая цена брокера/);
assert.match(core,/Положение последней свечи в диапазоне окна/);
assert.match(core,/Последняя свеча → цена брокера/);
assert.match(core,/Худшая просадка окна/);
assert.match(core,/пик → минимум эпизода/);
assert.match(core,/Разница между ними не называется дневной доходностью/);
assert.match(core,/rangePosition=summary&&summary\.max>summary\.min/);
assert.match(css,/v66 · asset price map \+ drawdown context/);
assert.match(css,/\.sb-asset-period__bridge/);
assert.doesNotMatch(core.slice(core.indexOf("function AssetPeriodCockpit"),core.indexOf("function ResultPeriodCockpit")),/рекомендую|купить|продать/iu);
console.log("coreAssetPriceMapV66: ok");