import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const css=readFileSync(new URL("../src/styles/fullShellSystems.css",import.meta.url),"utf8");
const main=readFileSync(new URL("../src/main.tsx",import.meta.url),"utf8");
assert.match(main,/workspaceWorldFinish\.css";import"\.\/styles\/fullShellSystems\.css"/);
assert.match(css,/Full shell design systems v23/);
for(const shell of["samurai","carbon","core","horizon","aurora","minimal"])assert.match(css,new RegExp('data-shell="'+shell+'"'));
for(const token of["--shell-font","--shell-radius","--shell-card-border","--shell-card-shadow","--shell-title-spacing"])assert.match(css,new RegExp(token));
assert.match(css,/SAMURAI — lacquer/);assert.match(css,/COSMOS — technical orbital console/);assert.match(css,/NEON — arcade\/synth instrument/);assert.match(css,/ZEN — editorial calm/);assert.match(css,/NORD — Scandinavian utility/);assert.match(css,/IMPERIUM — archival\/financial ledger/);
assert.match(css,/data-shell="carbon"\]\[data-workspace="home"\][^]*clip-path/);
assert.match(css,/data-shell="minimal"\]\[data-workspace="home"\][^]*double #9a6a2a/);
assert.match(css,/@media\(max-width:699px\)[^]*backdrop-filter:none!important[^]*-webkit-backdrop-filter:none!important/);
assert.doesNotMatch(css,/animation:/);assert.doesNotMatch(css,/url\(/);
console.log("full shell design systems regression: ok");