import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const lab=readFileSync(new URL("../src/goal/V3GoalScenarioLab.tsx",import.meta.url),"utf8");
const goal=readFileSync(new URL("../src/goal/V3Goal.tsx",import.meta.url),"utf8");
const app=readFileSync(new URL("../src/app/V3App.tsx",import.meta.url),"utf8");
const css=readFileSync(new URL("../src/styles/goalScenarioLab.css",import.meta.url),"utf8");
assert.match(goal,/const V3GoalScenarioLab=lazy/);assert.match(lab,/V3SectionSelector label="Режим сценария"/);assert.match(lab,/TAB_OPTIONS/);assert.doesNotMatch(lab,/v3-goal-scenario-tabs/);
assert.match(goal,/mode==="detailed"&&target&&trusted&&value!=null/);
assert.match(goal,/history:HistoryPoint\[\]/);
assert.match(app,/history={history}/);
for(const label of["Ваш сценарий","Исторический диапазон","Горизонт","Пополнение","Инфляция","Изменение цены","Доходность выплат","Индекс-сценарий"])assert.match(lab,new RegExp(label));
assert.match(lab,/EMPTY:Draft/);
assert.match(lab,/Расчёт не запускается из пустых полей/);
assert.match(lab,/не подставляет будущую доходность, инфляцию или взносы автоматически/);
assert.match(lab,/historical block bootstrap/i);
assert.match(lab,/P10/);assert.match(lab,/Медиана/);assert.match(lab,/P90/);
assert.match(lab,/не является прогнозом вероятности достижения цели/);
assert.doesNotMatch(lab,/Math\.random|expectedYield|buy|sell/i);
assert.match(lab,/import"\.\.\/styles\/goalScenarioLab\.css"/);
assert.match(css,/max-width:430px/);assert.match(css,/max-width:359px/);assert.match(css,/focus-visible/);
console.log("v3 goal scenario lab UI contracts: ok");
