import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
const src=readFileSync(new URL("../src/assets/V3Assets.tsx",import.meta.url),"utf8");
assert.match(src,/V3SectionSelector/);
assert.match(src,/label="Раздел портфеля"/);
assert.match(src,/value:"summary",label:"Сводка"/);
assert.match(src,/value:"positions",label:"Позиции"/);
assert.match(src,/value:"structure",label:"Структура"/);
assert.match(src,/value:"pro",label:"Профи"/);
assert.match(src,/showSummary=!samuraiReference&&\(mode==="simple"\|\|view==="summary"\)/);
assert.match(src,/showPositions=!samuraiReference&&mode==="detailed"&&view==="positions"/);
assert.match(src,/view==="structure"&&<Suspense/);
assert.match(src,/view==="pro"&&<Suspense/);
assert.match(src,/КАРТА КАПИТАЛА/);
assert.match(src,/setView\(next\);setOpen\(null\)/);
assert.doesNotMatch(src,/mode==="detailed"&&trusted&&<Suspense fallback=.*V3HoldingsExplorer/);
console.log("v3 portfolio progressive disclosure contracts: ok");
