import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import{ratioToPercent,clampPercent}from"../src/data/units.ts";
assert.equal(ratioToPercent(.25),25);
assert.equal(ratioToPercent(1),100);
assert.equal(ratioToPercent(null),null);
assert.equal(clampPercent(125),100);
assert.equal(clampPercent(-4),0);
const assets=readFileSync(new URL("../src/assets/V3Assets.tsx",import.meta.url),"utf8");
const summary=readFileSync(new URL("../src/assets/assetsWorkspaceSummary.ts",import.meta.url),"utf8");
const home=readFileSync(new URL("../src/home/V3Home.tsx",import.meta.url),"utf8");
const donut=readFileSync(new URL("../src/analysis/V3AllocationDonut.tsx",import.meta.url),"utf8");
const analysis=readFileSync(new URL("../src/analysis/V3Analysis.tsx",import.meta.url),"utf8");
const impact=readFileSync(new URL("../src/analysis/impactMap.ts",import.meta.url),"utf8");
const workspace=readFileSync(new URL("../src/assets/V3AssetWorkspace.tsx",import.meta.url),"utf8");
assert.match(assets,/ratioToPercent\(x\.weight\)/);
assert.match(assets,/\(summary\.top3\?\?0\)\*100/);
assert.match(summary,/item\.currentValue\/total/);
assert.match(home,/ratioToPercent\(x\.weight\)/);
assert.match(donut,/ratioToPercent\(w\)/);
assert.match(analysis,/ratioToPercent\(topRatio\)/);
assert.match(analysis,/V3ImpactTreemap/);
assert.match(impact,/weightPct:weight\*100/);
assert.match(workspace,/ratioToPercent\(position\.weight\)/);
console.log("v3 normalized weight-unit contracts: ok");
