import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{buildResultEvidenceV120}from"../src/core/resultReconciliationModelV120.ts";
const ui=readFileSync(new URL("../src/core/CoreResultReconciliationV120.tsx",import.meta.url),"utf8"),core=readFileSync(new URL("../src/core/SnowballCore.tsx",import.meta.url),"utf8"),css=readFileSync(new URL("../src/core/coreResultReconciliationV120.css",import.meta.url),"utf8");
const history=[{date:"2026-01-01",value:100,portfolio:100,imoex:100},{date:"2026-02-01",value:110,portfolio:105,imoex:null},{date:"2026-03-01",value:null,portfolio:108,imoex:103}];
test("v120 fails closed without trusted complete FACT inputs",()=>{assert.equal(buildResultEvidenceV120({totalResult:100,openPositionPl:20,realizedPayouts:10,trusted:false,history}),null);assert.equal(buildResultEvidenceV120({totalResult:null,openPositionPl:20,realizedPayouts:10,trusted:true,history}),null)});
test("v120 reports evidence coverage without deriving fake additive attribution",()=>{const m=buildResultEvidenceV120({totalResult:120,openPositionPl:50,realizedPayouts:30,trusted:true,history});assert.ok(m);assert.equal(m.historyPoints,3);assert.equal(m.valuePoints,2);assert.equal(m.benchmarkCommonPoints,2);assert.equal(Math.round(m.benchmarkCoveragePct!),67);assert.equal(m.startDate,"2026-01-01");assert.equal(m.endDate,"2026-03-01");assert.equal("otherRealizedEffects" in m,false)});
test("v120 UI explicitly protects non-additive semantics",()=>{assert.match(ui,/Три факта — три разных вопроса/);assert.match(ui,/не складывает эти числа/);assert.match(ui,/не вычисляет «остаток»/);assert.match(ui,/общих подтверждённых точках/);assert.doesNotMatch(ui,/otherRealizedEffects|componentsTotal/)});
test("v120 is mounted from trusted FACT and history inputs",()=>{assert.match(core,/CoreResultReconciliationV120/);assert.match(core,/totalResult=\{home\.profit\}/);assert.match(core,/openPositionPl=\{profit\}/);assert.match(core,/realizedPayouts=\{income\.total\}/);assert.match(core,/trusted=\{trusted\}/);assert.match(core,/history=\{history\}/)});
test("v120 is readable on phones and contains no action handlers",()=>{assert.match(css,/@media\(max-width:620px\)/);assert.match(css,/grid-template-columns:1fr/);assert.doesNotMatch(ui,/onClick|order|trade|targetPrice|forecast/iu)});
assert.match(ui,/Независимые факты результата/);assert.match(ui,/Покрытие доказательствами/);console.log("resultReconciliationV120: ok");
