import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const home=readFileSync(new URL("../src/home/V3Home.tsx",import.meta.url),"utf8");
const css=readFileSync(new URL("../src/styles/samuraiCommandDeck.css",import.meta.url),"utf8");
const main=readFileSync(new URL("../src/main.tsx",import.meta.url),"utf8");
assert.match(home,/shell==="samurai"\?<><section className="v3-samurai-scene"/);
assert.match(home,/className="v3-samurai-instruments"/);
assert.match(home,/:<><header className="v3-hero"/);
assert.match(css,/grid-template-columns:repeat\(4,1fr\)/);
assert.match(css,/height:clamp\(430px,59svh,500px\)/);
assert.match(main,/samuraiPosterDashboard\.css";import"\.\/styles\/samuraiCommandDeck\.css"/);
assert.ok(main.indexOf("samuraiCommandDeck.css")<main.indexOf("mobilePerformance.css"));
assert.doesNotMatch(css,/backdrop-filter|animation:/);
console.log("samurai dedicated command deck regression: ok");
