import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const gate=readFileSync(new URL("../src/samurai/SamuraiTrustGate.tsx",import.meta.url),"utf8");
const assets=readFileSync(new URL("../src/assets/V3Assets.tsx",import.meta.url),"utf8");
const analysis=readFileSync(new URL("../src/analysis/V3Analysis.tsx",import.meta.url),"utf8");
const income=readFileSync(new URL("../src/income/V3Income.tsx",import.meta.url),"utf8");
const css=readFileSync(new URL("../src/styles/samuraiTrustGates.css",import.meta.url),"utf8");
const main=readFileSync(new URL("../src/main.tsx",import.meta.url),"utf8");
for(const kind of["assets","analysis","income"])assert.match(gate,new RegExp(kind));
assert.match(gate,/FAIL-CLOSED/);
assert.doesNotMatch(gate,/\d+[\s\u00A0]*₽|\d+[,.]\d+%/);
assert.match(assets,/data-trusted=\{trusted\}/);assert.match(assets,/SamuraiTrustGate kind="assets"/);
assert.match(analysis,/data-trusted=\{trusted\}/);assert.match(analysis,/SamuraiTrustGate kind="analysis"/);
assert.match(income,/data-trusted=\{model\.trusted\}/);assert.match(income,/SamuraiTrustGate kind="income"/);
assert.match(css,/data-trusted="false"/);
assert.match(css,/min-height:315px!important/);
assert.match(css,/sam-trust-gate__route/);
assert.match(css,/prefers-reduced-motion:reduce/);
assert.ok(main.indexOf("samuraiVideoPolish.css")<main.indexOf("samuraiTrustGates.css"));
assert.ok(main.indexOf("samuraiTrustGates.css")<main.indexOf("mobilePerformance.css"));
console.log("samurai trust-gate regression: ok");