import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const ui=readFileSync(new URL("../src/samurai/SamuraiPrototype.tsx",import.meta.url),"utf8");
const baseCss=readFileSync(new URL("../src/styles/v3.css",import.meta.url),"utf8");
const repair=readFileSync(new URL("../src/styles/samuraiHomeTelemetryRepair.css",import.meta.url),"utf8");
const deck=readFileSync(new URL("../src/styles/samuraiHomeCommandDeck.css",import.meta.url),"utf8");
const inception=readFileSync(new URL("../src/styles/samuraiSinceInception.css",import.meta.url),"utf8");
const story=readFileSync(new URL("../src/styles/samuraiScrollStory.css",import.meta.url),"utf8");
const empty=readFileSync(new URL("../src/styles/samuraiEmptyAnalyticsAtmosphere.css",import.meta.url),"utf8");
const transition=readFileSync(new URL("../src/styles/samuraiScrollTransitionPolish.css",import.meta.url),"utf8");
const continuity=readFileSync(new URL("../src/styles/samuraiSecondaryContinuity.css",import.meta.url),"utf8");
const secondaryViewport=readFileSync(new URL("../src/styles/samuraiSecondaryViewportPolish.css",import.meta.url),"utf8");
const dock=readFileSync(new URL("../src/styles/samuraiFormationDock.css",import.meta.url),"utf8");
const app=readFileSync(new URL("../src/app/V3App.tsx",import.meta.url),"utf8");
const main=readFileSync(new URL("../src/main.tsx",import.meta.url),"utf8");

for(const x of["sam-world__scene-page","sam-world__analytics-page","sam-world__scroll-cue","sam-world__capital","sam-world__origin","sam-world__origin-metrics","sam-world__pulsemarks","sam-world__path","sam-world__formation","sam-world__awaiting"])assert.match(ui,new RegExp(x));
for(const x of["БОЛЬШЕ АНАЛИТИКИ","Аналитика","С МОМЕНТА ОТКРЫТИЯ","ДОСТУПНАЯ ИСТОРИЯ","ПОРТФЕЛЬ","IMOEX","ОПЕРЕЖЕНИЕ","Источник ещё не подтверждён","DATA GATE // FAIL-CLOSED"])assert.match(ui,new RegExp(x));
assert.ok(ui.includes('{home.isTrusted?<>'));
assert.match(ui,/scrollIntoView\(\{block:"start"\}\)/);
assert.match(ui,/id="samurai-analytics"/);
assert.match(ui,/buildV3RelativeDepth\(home\.history\)/);
assert.match(ui,/home\.openedDate/);
assert.match(ui,/home\.value/);
assert.match(ui,/home\.profit/);
assert.match(ui,/home\.xirr/);
assert.match(ui,/home\.passiveIncome/);
assert.match(ui,/home\.positions/);
assert.match(ui,/home\.leaders/);
assert.match(ui,/relative\.portfolioReturn/);
assert.match(ui,/relative\.benchmarkReturn/);
assert.match(ui,/relative\.excessReturn/);
assert.match(ui,/pairedGeometry\(home\.history\)/);
assert.doesNotMatch(ui,/1 284 760|184 320|18,7|21,4|84 620|24,8|18,1|31,6/);
assert.doesNotMatch(ui,/КРЯХТЯЩИЙ ФОНД/);
assert.doesNotMatch(ui,/sam-world__answer/);

assert.match(baseCss,/html,body,#root\{margin:0;width:100%;min-width:0;min-height:100%;padding:0\}/);
assert.match(baseCss,/body\{min-height:100dvh;overflow-x:hidden\}/);
assert.match(baseCss,/#root\{min-height:100dvh\}/);

assert.match(app,/SamuraiPrototype home=\{home\}/);
assert.match(app,/samuraiViewportLock=shell==="samurai"&&!home\.isTrusted&&\["assets","analysis","income","goal"\]\.includes\(workspace\)/);
assert.match(app,/data-viewport-lock=\{samuraiViewportLock\?"true":"false"\}/);
assert.match(app,/loadV3Analysis=\(\)=>import\("\.\.\/analysis\/V3Analysis"\)/);
assert.match(app,/V3Analysis=lazy\(loadV3Analysis\)/);
assert.match(app,/workspace==="analysis"\?<Suspense/);
assert.match(app,/void loadV3Analysis\(\);void loadV3AssetWorkspace\(\);void loadV3DnaWorkspace\(\)/);
assert.match(repair,/overflow:hidden!important/);
assert.match(deck,/sam-world__capital/);
assert.match(inception,/sam-world__origin/);
assert.match(dock,/sam-world__formation button:before/);

assert.match(story,/scroll-snap-type:y proximity/);
assert.match(story,/overflow-y:auto!important/);
assert.match(story,/sam-world__scene-page/);
assert.match(story,/height:100dvh/);
assert.match(story,/sam-world__analytics-page/);
assert.match(story,/filter:saturate\(1\.28\) contrast\(1\.09\) brightness\(1\.03\)/);
assert.match(story,/sam-world__scroll-cue/);
assert.match(story,/grid-template-columns:1fr 1fr!important/);
assert.match(story,/height:155px!important/);
assert.match(story,/prefers-reduced-motion:reduce/);

assert.match(empty,/sam-world__awaiting/);
assert.match(empty,/min-height:calc\(100dvh - 250px\)/);
assert.match(empty,/sam-world__awaiting-route/);
assert.match(empty,/sam-world__awaiting-art/);
assert.match(empty,/prefers-reduced-motion:reduce/);
assert.match(transition,/sam-world__scene-page:after/);
assert.match(transition,/padding-top:max\(42px,calc\(env\(safe-area-inset-top\) \+ 30px\)\)!important/);
assert.match(transition,/linear-gradient\(180deg,rgba\(2,7,6,.82\),rgba\(2,8,7,.90\)\)/);
assert.match(transition,/min-height:calc\(100dvh - 286px\)!important/);
assert.match(transition,/prefers-reduced-motion:reduce/);
assert.match(continuity,/padding-top:max\(20px,calc\(env\(safe-area-inset-top\) \+ 16px\)\)!important/);
assert.match(continuity,/data-workspace="assets"/);
assert.match(continuity,/data-workspace="analysis"/);
assert.match(continuity,/data-workspace="income"/);
assert.match(continuity,/var\(--samurai-ronin-art\)/);
assert.match(continuity,/v3-workspace-loading\[data-shell="samurai"\]/);
assert.match(continuity,/v3-workspace-loading__panel/);
assert.match(secondaryViewport,/height:calc\(100dvh - 48px\)!important/);
assert.match(secondaryViewport,/sam-workspace-chrome/);
assert.match(secondaryViewport,/display:none!important/);
assert.match(secondaryViewport,/sam-trust-gate--assets/);
assert.match(secondaryViewport,/sam-trust-gate--analysis/);
assert.match(secondaryViewport,/sam-trust-gate--income/);
assert.match(secondaryViewport,/v3-goal:has\(\.sam-goal-empty-path\)/);
assert.match(secondaryViewport,/\.v3-app\[data-shell="samurai"\]>.v3-topbar\{/);
assert.match(secondaryViewport,/box-sizing:border-box!important/);
assert.match(secondaryViewport,/html:has\(\.v3-app\[data-shell="samurai"\]\[data-workspace="assets"\]/);
assert.match(secondaryViewport,/body:has\(\.v3-app\[data-shell="samurai"\]\[data-workspace="analysis"\]/);
assert.match(secondaryViewport,/overflow:hidden!important/);
assert.match(secondaryViewport,/height:100dvh!important/);
assert.match(secondaryViewport,/data-viewport-lock="true"/);
assert.match(secondaryViewport,/position:fixed!important/);
assert.match(secondaryViewport,/inset:0!important/);
assert.match(secondaryViewport,/scrollbar-width:none!important/);
assert.match(secondaryViewport,/::-webkit-scrollbar/);

assert.ok(main.indexOf("samuraiHomeTelemetryRepair.css")<main.indexOf("samuraiHomeCommandDeck.css"));
assert.ok(main.indexOf("samuraiHomeCommandDeck.css")<main.indexOf("samuraiSinceInception.css"));
assert.ok(main.indexOf("samuraiSinceInception.css")<main.indexOf("samuraiScrollStory.css"));
assert.ok(main.indexOf("samuraiScrollStory.css")<main.indexOf("samuraiEmptyAnalyticsAtmosphere.css"));
assert.ok(main.indexOf("samuraiEmptyAnalyticsAtmosphere.css")<main.indexOf("samuraiScrollTransitionPolish.css"));
assert.ok(main.indexOf("samuraiScrollTransitionPolish.css")<main.indexOf("samuraiSecondaryContinuity.css"));
assert.ok(main.indexOf("samuraiSecondaryContinuity.css")<main.indexOf("samuraiSecondaryViewportPolish.css"));
assert.ok(main.indexOf("samuraiSecondaryViewportPolish.css")<main.indexOf("mobilePerformance.css"));
console.log("samurai compact metrics regression: ok");