import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const component=readFileSync(new URL("../src/navigation/V3SectionSelector.tsx",import.meta.url),"utf8");
const css=readFileSync(new URL("../src/styles/sectionSelector.css",import.meta.url),"utf8");
const analysis=readFileSync(new URL("../src/analysis/V3Analysis.tsx",import.meta.url),"utf8");
const income=readFileSync(new URL("../src/income/V3IncomeDepth.tsx",import.meta.url),"utf8");
const goal=readFileSync(new URL("../src/goal/V3GoalScenarioLab.tsx",import.meta.url),"utf8");
const holdings=readFileSync(new URL("../src/assets/V3HoldingsExplorer.tsx",import.meta.url),"utf8");
const portfolio=readFileSync(new URL("../src/assets/V3Assets.tsx",import.meta.url),"utf8");
const asset=readFileSync(new URL("../src/assets/V3AssetWorkspace.tsx",import.meta.url),"utf8");
const globalCss=readFileSync(new URL("../src/styles/v3.css",import.meta.url),"utf8");
assert.match(component,/export type V3SectionOption/);assert.match(component,/aria-haspopup="dialog"/);assert.match(component,/role="dialog"/);assert.match(component,/aria-modal="true"/);assert.match(component,/active\?\.description/);assert.match(component,/choose\(option\.value\)/);assert.doesNotMatch(component,/<select/);
for(const [source,label] of [[analysis,"Раздел аналитики"],[income,"Раздел дохода"],[goal,"Режим сценария"],[holdings,"Показать структуру по"],[portfolio,"Раздел портфеля"],[asset,"Раздел актива"]])assert.match(source,new RegExp('V3SectionSelector label="'+label+'"'));
for(const copy of["TWR, волатильность, Sharpe, Sortino","12-месячное расписание","Будущие предпосылки задаёте вы","нормализованному эмитенту","Классы, инструменты, эмитенты, отрасли и валюты"])assert.ok([analysis,income,goal,holdings,portfolio,asset].some(source=>source.includes(copy)),copy);
assert.match(css,/height:48px/);assert.match(css,/font:700 12px/);assert.match(css,/v3-section-sheet/);assert.match(css,/position:fixed/);assert.match(css,/border-radius:20px 20px 0 0/);assert.match(css,/focus-visible/);assert.match(css,/data-shell="horizon"/);assert.match(css,/data-shell="carbon"/);assert.match(css,/max-width:359px/);
assert.doesNotMatch(globalCss,/v3-analysis-tabs/);assert.doesNotMatch(income,/v3-income-depth-tabs/);assert.doesNotMatch(goal,/v3-goal-scenario-tabs/);
console.log("v3 shared section selector contracts: ok");
